/**
 * English UI strings (default). Shape is the source of truth for other locales.
 */
export const messagesEn = {
  meta: {
    title: 'Slicer profile browser',
    description: 'Browse Bambu Studio and OrcaSlicer process/filament profile inheritance',
  },
  header: {
    title: 'Slicer profile browser',
    subtitle: 'Profiles are read from this computer through the local API. Nothing is uploaded.',
    apiPrefix: 'API:',
    sourceLabel: 'Source:',
    layoutLabel: 'layout:',
    connectionHelp: 'How to connect',
  },
  dataSource: {
    modalTitle: 'Install or connect Slicer Profile Browser',
    modalIntro:
      'The desktop app is the easiest option. The hosted website always requires the local API to be running on the same computer.',
    desktopTitle: 'Recommended: download the desktop app',
    desktopBody:
      'Available for macOS and Windows. It starts the local API automatically, so no terminal or developer setup is needed.',
    downloadDesktop: 'Download desktop app',
    webTitle: 'Using the web app',
    webApiRequired:
      'The web app cannot read slicer profiles by itself. The local API must be running on this computer on macOS and Windows.',
    webBody:
      'You can use the hosted Vercel interface with a locally running API, or clone the repository and run both the API and interface yourself.',
    macPathTip: 'In Finder choose Go → Go to Folder… (⇧⌘G). The Library folder is normally hidden.',
    windowsPathTip:
      'Paste this path into the File Explorer address bar. It points to the usual Roaming AppData folder.',
    developerTitle: 'Developer setup',
    developerBody:
      'Run the commands below, then use the hosted web app. To run the interface locally as well, start npm run dev in a second terminal.',
    apiOptionalEnv: 'Optional: custom folder or port:',
    runUiLocally:
      'For a completely local web setup, run npm run dev in a second terminal and open http://localhost:3000.',
    checkApi: 'Check local API',
    close: 'Close',
  },
  controls: {
    extruderIndex: 'Extruder index',
    checkConnection: 'Check connection',
    retryApi: 'Retry API',
    checkConnectionTooltip:
      'Checks that the local API is reachable and that the selected slicer data folder is readable. Does not reload the profile list.',
    retryApiTooltip:
      'Tries to reconnect to the local API and read the selected slicer data folder.',
    connectionOk: 'Connected',
    connectionOkApiDescription: 'Reached the {slicer} API at {root}.',
    connectionFailed: 'Connection check failed',
    refreshList: 'Refresh list',
    bambuAccount: 'Bambu Lab Account',
    noAccounts: 'No accounts',
    showOnlyChanged: 'Show only changed values',
    slicer: 'Slicer',
    slicerBambu: 'Bambu',
    slicerOrca: 'Orca',
    orcaDefaultAccount: 'OrcaSlicer profiles use the default account.',
  },
  errors: {
    serverCannotReadRoot:
      'Server cannot read the selected slicer root: {root}. Check BAMBUSTUDIO_ROOT or ORCASLICER_ROOT.',
    cannotReachApi: 'Cannot reach the local API. Run: node server.js (see terminal).',
    loadProfilesFailed: 'Failed to load profiles',
    refreshFailed: 'Refresh failed',
    resolveInheritanceFailed: 'Failed to resolve inheritance',
  },
  offline: {
    webTitle: 'The local API is not running',
    webBody:
      'The web app cannot load profiles without the local API. Open “How to connect” for the desktop download and developer instructions.',
    desktopTitle: 'The bundled local API is not responding',
    desktopBody:
      'Restart the desktop app. If the problem continues, close any other process using port 3847 and try again.',
  },
  sidebar: {
    connectFirst: 'Connect first: open “How to connect” in the header, or check the connection.',
    loading: 'Loading…',
    emptyProfiles: 'No JSON profiles found. Check the selected slicer path and account folders.',
    groupCustomFilaments: 'Custom filaments',
    groupFilament: 'Filaments',
    groupProcess: 'Process',
  },
  main: {
    resolving: 'Resolving inheritance…',
  },
  treeGrid: {
    emptyHint:
      'Load a filament or process to show the inheritance tree (one column per template in the chain).',
    columnProperty: 'Property',
    filterLabel: 'Filter',
    propertySearchPlaceholder: 'Filter by property name…',
    copyToClipboard: 'Copy to clipboard',
    downloadProfile: 'Download profile',
    editProfile: 'Edit profile',
    fileNameCopied: 'File name {filename} copied to clipboard',
    fileCopied: 'File {filename} copied to clipboard',
    fileDownloaded: 'File {filename} downloaded',
    customFileCopied: 'Custom file {filename} copied to clipboard',
    customFileDownloaded: 'Custom file {filename} downloaded',
    copyFailed: 'Could not copy to clipboard',
  },
  profileEditor: {
    title: 'Edit profile file',
    intro: 'Edit the original leaf JSON. Inherits, type, name, and from cannot be changed.',
    format: 'Format',
    validate: 'Validate',
    save: 'Save',
    showChanges: 'Show changes',
    backToEditing: 'Back to editing',
    noChanges: 'No changes compared to the file on disk.',
    diffLayout: 'Diff layout',
    diffInline: 'Inline diff',
    diffSideBySide: 'Side-by-side diff',
    changedFields: 'Changed fields in this leaf profile',
    discard: 'Discard changes',
    cancel: 'Cancel',
    minimize: 'Minimize',
    maximize: 'Maximize',
    keepEditing: 'Keep editing',
    confirmDiscard: 'Discard unsaved changes?',
    confirmDiscardBody: 'Your edits have not been saved. This action cannot be undone.',
    loading: 'Loading profile file…',
    validationPassed: 'Validation passed',
    validationWarnings: 'Validation passed with warnings ({count})',
    validationFailed: 'Validation failed',
    revertLockedFields: 'Revert',
    revertLockedFailed: 'Could not restore locked fields',
    noValidationFindings: 'No validation issues found.',
    severityBlocker: 'Blocker',
    severityError: 'Error',
    severityWarning: 'Warning',
    formatFailed: 'Could not format JSON',
    saveFailed: 'Could not save profile',
    saved: 'Profile updated and reloaded',
    savedDescription: 'The leaf file was replaced and the profile was reloaded.',
    writePermissionDenied: 'Write access to the Bambu Studio folder was denied.',
  },
  compareFilament: {
    materialsHeading: 'Material',
    brandsHeading: 'Brand / line',
    foldersHeading: 'Folders',
    rootToggle: 'Root',
    rootFolder: 'Root folder',
    label: 'Compare to a filament',
    placeholderClosed: 'Select a system filament…',
    searchPlaceholder: 'Search filaments…',
    loadingList: 'Loading list…',
    noMatches: 'No matching filaments',
    removeAria: 'Remove',
    removeTooltip: 'Remove',
  },
  chainColumn: {
    profileFilament: 'Filament profile',
    profileProcess: 'Process profile',
    root: 'Root',
    parent: 'Parent',
    level: 'Level {n}',
  },
  propertyTooltip: {
    aboutAria: 'About {label}',
  },
  theme: {
    label: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    frostedAura: 'Frosted Aura',
    inked: 'Inked',
    slate: 'Slate',
    frozenMist: 'Frozen Mist',
    sapphireNightfall: 'Sapphire Nightfall',
    amethystDawnHaze: 'Amethyst Dawn Haze',
    aria: 'Color theme',
  },
  language: {
    label: 'Language',
    en: 'English',
    nb: 'Norwegian',
    aria: 'Interface language',
  },
};

export type Messages = typeof messagesEn;
