import type { AppLocale } from "./types";

const GROUP_LABELS: Readonly<Record<string, readonly [string, string]>> = {
  "additional-settings": ["Additional settings", "Flere innstillinger"],
  cooling: ["Cooling", "Kjøling"],
  filament: ["Filament", "Filament"],
  metadata: ["Metadata", "Metadata"],
  others: ["Others", "Annet"],
  quality: ["Quality", "Kvalitet"],
  "setting-overrides": ["Setting Overrides", "Overstyringer"],
  speed: ["Speed", "Hastighet"],
  strength: ["Strength", "Styrke"],
  support: ["Support", "Støtte"],
};

const SUBGROUP_LABELS: Readonly<Record<string, readonly [string, string]>> = {
  "cooling-aux": ["Auxiliary part cooling fan", "Ekstra delekjølevifte"],
  "cooling-part-fan": ["Part cooling fan", "Delekjølevifte"],
  "cooling-specific-layer": [
    "Cooling for specific layer",
    "Kjøling for bestemte lag",
  ],
  "dimensional-compensation": [
    "Dimensional compensation",
    "Dimensjonskompensasjon",
  ],
  "extrusion-change": [
    "Extrusion and material changes",
    "Ekstrudering og materialbytte",
  ],
  "filament-basic": ["Basic information", "Grunnleggende informasjon"],
  "filament-print-temp": ["Print temperature", "Utskriftstemperatur"],
  "filament-scarf": ["Filament scarf seam settings", "Skjerfsøm for filament"],
  "filament-volumetric": [
    "Volumetric speed limitation",
    "Begrensning av volumhastighet",
  ],
  "material-properties": ["Material properties", "Materialegenskaper"],
  metadata: ["Profile metadata", "Profilmetadata"],
  "other-settings": ["Other settings", "Andre innstillinger"],
  "output-additional": [
    "Output and auxiliary structures",
    "Utdata og hjelpestrukturer",
  ],
  "overrides-retraction": ["Retraction", "Retraction"],
  "overrides-speed": ["Speed", "Hastighet"],
  "quality-additional": [
    "Additional quality settings",
    "Flere kvalitetsinnstillinger",
  ],
  "quality-layer-height": ["Layer height", "Laghøyde"],
  "quality-line-width": ["Line width", "Linjebredde"],
  "quality-precision": ["Precision", "Presisjon"],
  "quality-wall-seam": ["Wall & seam", "Vegg og søm"],
  "speed-acceleration": ["Acceleration", "Akselerasjon"],
  "speed-additional": [
    "Additional speed settings",
    "Flere hastighetsinnstillinger",
  ],
  "speed-print": ["Print speed", "Utskriftshastighet"],
  "strength-additional": [
    "Additional strength settings",
    "Flere styrkeinnstillinger",
  ],
  "strength-infill": ["Infill", "Utfylling"],
  "strength-walls": ["Walls", "Vegger"],
  "support-additional": [
    "Additional support settings",
    "Flere støtteinnstillinger",
  ],
  "support-advanced": ["Advanced", "Avansert"],
  "support-basic": ["Support", "Støtte"],
  "thermal-cooling": [
    "Temperature, drying and cooling",
    "Temperatur, tørking og kjøling",
  ],
  "others-brim": ["Brim", "Brem"],
  "others-prime-tower": ["Prime tower", "Rensetårn"],
  "others-skirt": ["Skirt", "Skjørt"],
};

const SPECIAL_NB_LABELS: Readonly<Record<string, string>> = {
  additional_cooling_fan_speed: "Hastighet for ekstra kjølevifte",
  bottom_shell_layers: "Antall bunnlag",
  bridge_flow: "Flyt for broer",
  brim_object_gap: "Avstand mellom brem og objekt",
  brim_width: "Brembredde",
  close_fan_the_first_x_layers: "Slå av viften for de første lagene",
  cool_plate_temp: "Temperatur for Cool Plate – øvrige lag",
  cool_plate_temp_initial_layer: "Temperatur for Cool Plate – første lag",
  default_acceleration: "Standardakselerasjon",
  default_filament_colour: "Standard filamentfarge",
  elefant_foot_compensation: "Kompensasjon for elefantfot",
  enable_arc_fitting: "Aktiver buetilpasning",
  enable_prime_tower: "Aktiver rensetårn",
  enable_support: "Aktiver støtte",
  eng_plate_temp: "Temperatur for Engineering Plate – øvrige lag",
  eng_plate_temp_initial_layer: "Temperatur for Engineering Plate – første lag",
  fan_cooling_layer_time: "Lagtid ved minimum viftehastighet",
  fan_max_speed: "Maksimal viftehastighet",
  fan_min_speed: "Minimal viftehastighet",
  filament_cost: "Filamentpris",
  filament_density: "Filamenttetthet",
  filament_diameter: "Filamentdiameter",
  filament_flow_ratio: "Flytforhold",
  filament_max_volumetric_speed: "Maksimal volumhastighet",
  filament_retraction_length: "Retaksjonslengde",
  filament_retraction_speed: "Retaksjonshastighet",
  filament_shrink: "Krymping",
  filament_type: "Filamenttype",
  filament_vendor: "Filamentleverandør",
  hot_plate_temp: "Temperatur for glatt PEI / High Temp Plate – øvrige lag",
  hot_plate_temp_initial_layer:
    "Temperatur for glatt PEI / High Temp Plate – første lag",
  infill_direction: "Retning for utfylling",
  infill_wall_overlap: "Overlapping mellom utfylling og vegg",
  initial_layer_line_width: "Linjebredde for første lag",
  initial_layer_print_height: "Høyde for første lag",
  initial_layer_speed: "Hastighet for første lag",
  inner_wall_line_width: "Linjebredde for innervegg",
  inner_wall_speed: "Hastighet for innervegg",
  internal_solid_infill_line_width:
    "Linjebredde for massiv innvendig utfylling",
  layer_height: "Laghøyde",
  line_width: "Standard linjebredde",
  name: "Navn",
  nozzle_temperature: "Dysetemperatur – øvrige lag",
  nozzle_temperature_initial_layer: "Dysetemperatur – første lag",
  nozzle_temperature_range_high: "Anbefalt maksimal dysetemperatur",
  nozzle_temperature_range_low: "Anbefalt minimal dysetemperatur",
  outer_wall_line_width: "Linjebredde for yttervegg",
  outer_wall_speed: "Hastighet for yttervegg",
  prime_tower_width: "Bredde på rensetårn",
  seam_position: "Sømplassering",
  skirt_distance: "Skjørtavstand",
  skirt_height: "Skjørthøyde",
  skirt_loops: "Antall skjørtlinjer",
  slow_down_for_layer_cooling: "Senk hastigheten for bedre lagkjøling",
  sparse_infill_density: "Tetthet for sparsom utfylling",
  sparse_infill_line_width: "Linjebredde for sparsom utfylling",
  sparse_infill_pattern: "Mønster for sparsom utfylling",
  sparse_infill_speed: "Hastighet for sparsom utfylling",
  support_bottom_z_distance: "Nedre Z-avstand for støtte",
  support_on_build_plate_only: "Støtte bare på byggeplaten",
  support_style: "Støttestil",
  support_threshold_angle: "Terskelvinkel for støtte",
  support_top_z_distance: "Øvre Z-avstand for støtte",
  support_type: "Støttetype",
  temperature_vitrification: "Mykningstemperatur",
  textured_plate_temp: "Temperatur for teksturert PEI – øvrige lag",
  textured_plate_temp_initial_layer:
    "Temperatur for teksturert PEI – første lag",
  top_shell_layers: "Antall topplag",
  top_surface_line_width: "Linjebredde for toppflate",
  travel_acceleration: "Forflytningsakselerasjon",
  travel_speed: "Forflytningshastighet",
  type: "Type",
  wall_generator: "Vegggenerator",
  wall_infill_order: "Rekkefølge for vegg og utfylling",
  wall_loops: "Antall vegglinjer",
};

const NB_WORDS: Readonly<Record<string, string>> = {
  acceleration: "akselerasjon",
  activate: "aktiver",
  adaptation: "tilpasning",
  adaptive: "adaptiv",
  additional: "ekstra",
  air: "luft",
  angle: "vinkel",
  area: "område",
  arc: "bue",
  avoid: "unngå",
  away: "bort",
  axis: "akse",
  base: "grunn",
  bed: "byggeplate",
  before: "før",
  bottom: "bunn",
  branch: "gren",
  bridge: "bro",
  brim: "brem",
  build: "byggeplate",
  chamber: "kammer",
  change: "bytte",
  changing: "bytte",
  circle: "sirkel",
  close: "slå av",
  coefficient: "koeffisient",
  coefficients: "koeffisienter",
  coef: "koeffisient",
  color: "farge",
  colour: "farge",
  combination: "kombinasjon",
  common: "felles",
  compatibility: "kompatibilitet",
  compensation: "kompensasjon",
  compatible: "kompatible",
  complete: "fullført",
  condition: "betingelse",
  contact: "kontakt",
  contour: "kontur",
  continuous: "kontinuerlig",
  cool: "kjøleplate",
  cooling: "kjøling",
  cost: "pris",
  count: "antall",
  counter: "innsnevring",
  crossing: "kryssing",
  cut: "kutting",
  default: "standard",
  delta: "forskjell",
  density: "tetthet",
  depth: "dybde",
  deretraction: "deretaksjon",
  detect: "oppdag",
  detection: "oppdagelse",
  detour: "omvei",
  dev: "utvikler",
  diameter: "diameter",
  direction: "retning",
  dist: "avstand",
  distance: "avstand",
  distances: "avstander",
  distortion: "deformasjon",
  down: "ned",
  draft: "trekk",
  drying: "tørking",
  during: "under",
  elefant: "elefant",
  emission: "utslipp",
  enable: "aktiver",
  end: "slutt",
  eng: "teknisk plate",
  exhaust: "avtrekk",
  expansion: "utvidelse",
  extruder: "ekstruder",
  extrusion: "ekstrudering",
  extra: "ekstra",
  factor: "faktor",
  fan: "vifte",
  fast: "rask",
  features: "funksjoner",
  filament: "filament",
  filename: "filnavn",
  fill: "fyll",
  filtration: "filtrering",
  first: "første",
  fitting: "tilpasning",
  flat: "flat",
  floating: "flytende",
  flow: "flyt",
  flush: "spyling",
  foot: "fot",
  for: "for",
  format: "format",
  framework: "rammeverk",
  freq: "frekvens",
  from: "fra",
  full: "full",
  fuzzy: "lodden",
  gap: "mellomrom",
  gcode: "G-kode",
  generator: "generator",
  heat: "varme",
  height: "høyde",
  high: "høy",
  hole: "hull",
  hop: "løft",
  hot: "varm",
  impact: "slag",
  includes: "inkluderer",
  infill: "utfylling",
  ingredients: "ingredienser",
  initial: "første",
  inner: "indre",
  inset: "innrykk",
  instantiation: "instansiering",
  instead: "i stedet",
  interface: "grensesnitt",
  internal: "innvendig",
  into: "inn i",
  ironing: "stryking",
  is: "er",
  lattice: "gitter",
  layer: "lag",
  layers: "lag",
  length: "lengde",
  limitations: "begrensninger",
  lift: "løft",
  limit: "grense",
  line: "linje",
  lock: "låsing",
  locked: "låst",
  logic: "logikk",
  long: "lang",
  loop: "linje",
  loops: "linjer",
  low: "lav",
  manual: "manuell",
  material: "materiale",
  max: "maks",
  maximum: "maksimum",
  metal: "metall",
  min: "min",
  minimal: "minimal",
  minimum: "minimum",
  mode: "modus",
  monotonic: "monoton",
  multiline: "flerlinjet",
  name: "navn",
  no: "ikke",
  noise: "støy",
  nozzle: "dyse",
  object: "objekt",
  octaves: "oktaver",
  offset: "forskyvning",
  on: "på",
  one: "én",
  only: "bare",
  order: "rekkefølge",
  outer: "ytre",
  outwall: "yttervegg",
  outwalls: "yttervegger",
  overhang: "overheng",
  overhangs: "overheng",
  overlap: "overlapping",
  override: "overstyr",
  pattern: "mønster",
  per: "per",
  perimeter: "omkrets",
  placement: "plassering",
  penetration: "gjennomtrengning",
  persistence: "varighet",
  plate: "plate",
  point: "punkt",
  position: "plassering",
  pre: "før",
  preheat: "forvarming",
  prime: "rense",
  print: "utskrift",
  printable: "utskrivbar",
  printers: "skrivere",
  process: "prosess",
  purge: "rensing",
  raft: "flåte",
  ramming: "stamping",
  range: "område",
  ratio: "forhold",
  reduce: "reduser",
  required: "påkrevd",
  resolution: "oppløsning",
  restart: "omstart",
  retract: "retaksjon",
  retraction: "retaksjon",
  retractions: "retaksjoner",
  rotate: "rotasjon",
  safe: "trygg",
  scale: "skala",
  scarf: "skjerfsøm",
  seam: "søm",
  sequence: "rekkefølge",
  setting: "innstilling",
  settings: "innstillinger",
  shell: "skall",
  shells: "skall",
  shift: "forskyvning",
  short: "kort",
  shrink: "krymping",
  shield: "skjold",
  skeleton: "skjelett",
  skin: "hud",
  skirt: "skjørt",
  slope: "skråning",
  slow: "langsom",
  slowdown: "nedbremsing",
  smooth: "jevn",
  smoothing: "utjevning",
  softening: "mykning",
  solid: "massiv",
  soluble: "løselig",
  sparse: "sparsom",
  speed: "hastighet",
  spacing: "avstand",
  spiral: "spiral",
  standby: "ventemodus",
  start: "start",
  step: "trinn",
  stickiness: "klebrighet",
  stop: "stopp",
  strength: "styrke",
  style: "stil",
  supertack: "SuperTack",
  support: "støtte",
  surface: "flate",
  surfaces: "flater",
  symmetric: "symmetrisk",
  temp: "temperatur",
  temperature: "temperatur",
  temperatures: "temperaturer",
  textured: "teksturert",
  the: "de",
  thickness: "tykkelse",
  thin: "tynn",
  threshold: "terskel",
  time: "tid",
  top: "topp",
  totally: "fullstendig",
  tower: "tårn",
  transition: "overgang",
  travel: "forflytning",
  tree: "tre",
  type: "type",
  types: "typer",
  variant: "variant",
  velocity: "hastighet",
  vendor: "leverandør",
  vertical: "vertikal",
  vitrification: "mykning",
  volume: "volum",
  volumetric: "volumetrisk",
  wall: "vegg",
  walls: "vegger",
  when: "ved",
  width: "bredde",
  wipe: "tørking",
  wrapping: "vridning",
  y: "Y",
};

const ENUM_VALUES: Readonly<Record<string, readonly [string, string]>> = {
  aligned: ["Aligned", "Justert"],
  auto: ["Automatic", "Automatisk"],
  automatic: ["Automatic", "Automatisk"],
  classic: ["Classic", "Klassisk"],
  disabled: ["Disabled", "Deaktivert"],
  enabled: ["Enabled", "Aktivert"],
  grid: ["Grid", "Rutenett"],
  manual: ["Manual", "Manuell"],
  monotonic: ["Monotonic", "Monoton"],
  normal: ["Normal", "Normal"],
  organic: ["Organic", "Organisk"],
  rectilinear: ["Rectilinear", "Rettlinjet"],
  tree: ["Tree", "Tre"],
};

const TECHNICAL_TOKENS = new Set([
  "1",
  "2",
  "3",
  "4",
  "ams",
  "ec",
  "hrc",
  "id",
  "nc",
  "x",
  "xy",
  "z",
]);

function titleCase(text: string): string {
  return text.length > 0 ? text[0]!.toUpperCase() + text.slice(1) : text;
}

function humanizeEnglishKey(key: string): string {
  return titleCase(
    key
      .split("_")
      .map((word) => {
        const upper = word.toUpperCase();
        return ["AMS", "HRC", "ID", "NC", "XY", "Z"].includes(upper)
          ? upper
          : word;
      })
      .join(" "),
  );
}

function humanizeNorwegianKey(key: string): string {
  return titleCase(
    key
      .split("_")
      .map((word) => NB_WORDS[word.toLowerCase()] ?? word.toUpperCase())
      .join(" "),
  );
}

export function hasCompleteNorwegianLabel(key: string): boolean {
  return (
    Object.prototype.hasOwnProperty.call(SPECIAL_NB_LABELS, key) ||
    key
      .toLowerCase()
      .split("_")
      .every(
        (word) =>
          Object.prototype.hasOwnProperty.call(NB_WORDS, word) ||
          TECHNICAL_TOKENS.has(word),
      )
  );
}

export function localizedGroupLabel(
  id: string,
  fallback: string,
  locale: AppLocale,
): string {
  const labels = GROUP_LABELS[id];
  return labels?.[locale === "nb" ? 1 : 0] ?? fallback;
}

export function localizedSubgroupLabel(
  id: string,
  fallback: string,
  locale: AppLocale,
): string {
  const labels = SUBGROUP_LABELS[id];
  return labels?.[locale === "nb" ? 1 : 0] ?? fallback;
}

export function localizedPropertyLabel(
  key: string,
  englishFallback: string,
  locale: AppLocale,
): string {
  if (locale === "en") {
    return englishFallback === key ? humanizeEnglishKey(key) : englishFallback;
  }
  return SPECIAL_NB_LABELS[key] ?? humanizeNorwegianKey(key);
}

export function localizedBoolean(value: boolean, locale: AppLocale): string {
  if (locale === "nb") return value ? "Ja" : "Nei";
  return value ? "Yes" : "No";
}

export function localizedEnumValue(value: string, locale: AppLocale): string {
  const entry = ENUM_VALUES[value.trim().toLowerCase()];
  return entry?.[locale === "nb" ? 1 : 0] ?? value;
}
