/**
 * Generated by scripts/generate-profile-config-bounds.mjs.
 * Source: https://raw.githubusercontent.com/bambulab/BambuStudio/master/src/libslic3r/PrintConfig.cpp; do not edit manually.
 *
 * Declared option types and limits from Bambu Studio, which are authoritative
 * in a way that ranges observed across shipped profiles are not.
 */
export type ProfileConfigDef = {
  type: string;
  min?: number;
  max?: number;
  enumValues?: readonly string[];
};

export const PROFILE_CONFIG_DEFS: Readonly<Record<string, ProfileConfigDef>> = {
  absolute_correction: {
    type: "coFloat",
  },
  accel_to_decel_enable: {
    type: "coBool",
  },
  accel_to_decel_factor: {
    type: "coPercent",
    min: 1,
    max: 100,
  },
  activate_air_filtration: {
    type: "coBools",
  },
  adaptive_layer_height: {
    type: "coBool",
  },
  additional_cooling_fan_speed: {
    type: "coInts",
    min: 0,
    max: 100,
  },
  additional_fan_full_speed_layer: {
    type: "coInts",
    min: 0,
    max: 100000,
  },
  align_xy: {
    type: "coPoint",
  },
  allow_mix_temp: {
    type: "coBool",
  },
  allow_multicolor_oneplate: {
    type: "coBool",
  },
  allow_newer_file: {
    type: "coBool",
  },
  allow_rotations: {
    type: "coBool",
  },
  alternate_extra_wall: {
    type: "coBool",
  },
  ams_filament_load_time_ams: {
    type: "coFloat",
    min: 0,
  },
  ams_filament_load_time_ams_lite: {
    type: "coFloat",
    min: 0,
  },
  ams_filament_load_time_n3f_s: {
    type: "coFloat",
    min: 0,
  },
  ams_filament_unload_time_ams: {
    type: "coFloat",
    min: 0,
  },
  ams_filament_unload_time_ams_lite: {
    type: "coFloat",
    min: 0,
  },
  ams_filament_unload_time_n3f_s: {
    type: "coFloat",
    min: 0,
  },
  apply_scarf_seam_on_circles: {
    type: "coBool",
  },
  area_fill: {
    type: "coFloat",
    min: 0,
  },
  arrange: {
    type: "coInt",
  },
  assemble: {
    type: "coBool",
  },
  autosave: {
    type: "coString",
  },
  auxiliary_fan: {
    type: "coBool",
  },
  avoid_crossing_wall_includes_support: {
    type: "coBool",
  },
  avoid_extrusion_cali_region: {
    type: "coBool",
  },
  bed_custom_model: {
    type: "coString",
  },
  bed_custom_texture: {
    type: "coString",
  },
  bed_exclude_area: {
    type: "coPoints",
  },
  bed_heat_soak_area: {
    type: "coPoints",
  },
  bed_temperature_formula: {
    type: "coEnum",
    enumValues: ["by_first_filament", "by_highest_temp"],
  },
  before_layer_change_gcode: {
    type: "coString",
  },
  best_object_pos: {
    type: "coPoint",
  },
  bottle_cost: {
    type: "coFloat",
    min: 0,
  },
  bottle_volume: {
    type: "coFloat",
    min: 50,
  },
  bottle_weight: {
    type: "coFloat",
    min: 0,
  },
  bottom_color_penetration_layers: {
    type: "coInt",
    min: 1,
  },
  bottom_shell_layers: {
    type: "coInt",
    min: 0,
  },
  bottom_shell_thickness: {
    type: "coFloat",
    min: 0,
  },
  bottom_surface_density: {
    type: "coPercent",
    min: 10,
    max: 100,
  },
  bottom_surface_pattern: {
    type: "coEnum",
  },
  bridge_angle: {
    type: "coFloat",
    min: 0,
  },
  bridge_flow: {
    type: "coFloat",
    min: 0,
    max: 2,
  },
  bridge_no_support: {
    type: "coBool",
  },
  bridge_speed: {
    type: "coFloats",
    min: 0,
  },
  brim_object_gap: {
    type: "coFloat",
    min: 0,
    max: 2,
  },
  brim_type: {
    type: "coEnum",
    enumValues: [
      "auto_brim",
      "brim_ears",
      "outer_only",
      "inner_only",
      "outer_and_inner",
      "no_brim",
    ],
  },
  brim_width: {
    type: "coFloat",
    min: 0,
    max: 100,
  },
  camera_view: {
    type: "coInt",
  },
  center: {
    type: "coPoint",
  },
  chamber_temperatures: {
    type: "coInts",
    min: 0,
    max: 80,
  },
  change_filament_gcode: {
    type: "coString",
  },
  check_preset: {
    type: "coBool",
  },
  circle_compensation_manual_offset: {
    type: "coFloat",
  },
  circle_compensation_speed: {
    type: "coFloats",
    min: 0,
  },
  clone_objects: {
    type: "coInts",
  },
  close_additional_fan_first_x_layers: {
    type: "coInts",
    min: 0,
    max: 100000,
  },
  close_fan_the_first_x_layers: {
    type: "coInts",
    min: 0,
    max: 100000,
  },
  compatible_machine_expression_group: {
    type: "coStrings",
  },
  compatible_printers: {
    type: "coStrings",
  },
  compatible_printers_condition: {
    type: "coString",
  },
  compatible_prints: {
    type: "coStrings",
  },
  compatible_prints_condition: {
    type: "coString",
  },
  compatible_process_expression_group: {
    type: "coStrings",
  },
  complete_print_exhaust_fan_speed: {
    type: "coInts",
    min: 0,
    max: 100,
  },
  config_compatibility: {
    type: "coEnum",
    enumValues: ["disable", "enable", "enable_silent"],
  },
  convert_unit: {
    type: "coBool",
  },
  cool_plate_temp: {
    type: "coInts",
    min: 0,
    max: 120,
  },
  cool_plate_temp_initial_layer: {
    type: "coInts",
    min: 0,
    max: 120,
  },
  cooling_filter_enabled: {
    type: "coBool",
  },
  cooling_perimeter_transition_distance: {
    type: "coFloats",
    min: 0,
    max: 50,
  },
  cooling_slowdown_logic: {
    type: "coEnums",
    enumValues: ["uniform_cooling", "consistent_surface"],
  },
  copy: {
    type: "coInt",
    min: 1,
  },
  counter_coef_1: {
    type: "coFloats",
  },
  counter_coef_2: {
    type: "coFloats",
  },
  counter_coef_3: {
    type: "coFloats",
  },
  counter_limit_max: {
    type: "coFloats",
  },
  counter_limit_min: {
    type: "coFloats",
  },
  counterbore_hole_bridging: {
    type: "coEnum",
    enumValues: ["none", "partiallybridge", "sacrificiallayer"],
  },
  curr_bed_type: {
    type: "coEnum",
    enumValues: [
      "Cool Plate",
      "Engineering Plate",
      "High Temp Plate",
      "Textured PEI Plate",
      "Supertack Plate",
    ],
  },
  cut: {
    type: "coFloat",
  },
  cut_grid: {
    type: "coFloat",
  },
  cut_x: {
    type: "coFloat",
  },
  cut_y: {
    type: "coFloat",
  },
  datadir: {
    type: "coString",
  },
  debug: {
    type: "coInt",
    min: 0,
  },
  default_acceleration: {
    type: "coFloats",
    min: 0,
  },
  default_ams_type: {
    type: "coInt",
  },
  default_filament_colour: {
    type: "coStrings",
  },
  default_filament_profile: {
    type: "coStrings",
  },
  default_jerk: {
    type: "coFloat",
    min: 0,
  },
  default_nozzle_volume_type: {
    type: "coEnums",
  },
  default_print_profile: {
    type: "coString",
  },
  default_sla_material_profile: {
    type: "coString",
  },
  default_sla_print_profile: {
    type: "coString",
  },
  deretraction_speed: {
    type: "coFloats",
  },
  detect_floating_vertical_shell: {
    type: "coBool",
  },
  detect_narrow_internal_solid_infill: {
    type: "coBool",
  },
  detect_overhang_wall: {
    type: "coBool",
  },
  detect_thin_wall: {
    type: "coBool",
  },
  diameter_limit: {
    type: "coFloats",
  },
  different_settings_to_system: {
    type: "coStrings",
  },
  display_height: {
    type: "coFloat",
    min: 1,
  },
  display_mirror_x: {
    type: "coBool",
  },
  display_mirror_y: {
    type: "coBool",
  },
  display_orientation: {
    type: "coEnum",
    enumValues: ["landscape", "portrait"],
  },
  display_pixels_x: {
    type: "coInt",
    min: 100,
  },
  display_pixels_y: {
    type: "coInt",
    min: 100,
  },
  display_width: {
    type: "coFloat",
    min: 1,
  },
  downward_check: {
    type: "coBool",
  },
  downward_settings: {
    type: "coStrings",
  },
  draft_shield: {
    type: "coEnum",
    enumValues: ["disabled", "limited", "enabled"],
  },
  duplicate_grid: {
    type: "coPoint",
  },
  during_print_exhaust_fan_speed: {
    type: "coInts",
    min: 0,
    max: 100,
  },
  elefant_foot_compensation: {
    type: "coFloat",
    min: 0,
  },
  elefant_foot_min_width: {
    type: "coFloat",
    min: 0,
  },
  embedding_wall_into_infill: {
    type: "coBool",
  },
  enable_arc_fitting: {
    type: "coBool",
  },
  enable_circle_compensation: {
    type: "coBool",
  },
  enable_filament_dynamic_map: {
    type: "coBool",
  },
  enable_height_slowdown: {
    type: "coBools",
  },
  enable_long_retraction_when_cut: {
    type: "coInt",
  },
  enable_mixed_color_sublayer: {
    type: "coBool",
  },
  enable_order_independent_overlap_carving: {
    type: "coBool",
  },
  enable_overhang_bridge_fan: {
    type: "coBools",
  },
  enable_overhang_speed: {
    type: "coBools",
  },
  enable_pre_heating: {
    type: "coBool",
  },
  enable_pressure_advance: {
    type: "coBools",
  },
  enable_prime_tower: {
    type: "coBool",
  },
  enable_support: {
    type: "coBool",
  },
  enable_support_ironing: {
    type: "coBool",
  },
  enable_timelapse: {
    type: "coBool",
  },
  enable_tower_interface_features: {
    type: "coBool",
  },
  enable_wrapping_detection: {
    type: "coBool",
  },
  enforce_support_layers: {
    type: "coInt",
    min: 0,
    max: 5000,
  },
  eng_plate_temp: {
    type: "coInts",
    min: 0,
    max: 120,
  },
  eng_plate_temp_initial_layer: {
    type: "coInts",
    min: 0,
    max: 120,
  },
  ensure_on_bed: {
    type: "coBool",
  },
  ensure_vertical_shell_thickness: {
    type: "coEnum",
    enumValues: ["disabled", "partial", "enabled"],
  },
  estimate_mode: {
    type: "coBool",
  },
  exclude_object: {
    type: "coBool",
  },
  export_3mf: {
    type: "coString",
  },
  export_amf: {
    type: "coBool",
  },
  export_gcode: {
    type: "coBool",
  },
  export_obj: {
    type: "coBool",
  },
  export_png: {
    type: "coInt",
  },
  export_settings: {
    type: "coString",
  },
  export_sla: {
    type: "coBool",
  },
  export_slicedata: {
    type: "coString",
  },
  export_stl: {
    type: "coBool",
  },
  export_stls: {
    type: "coString",
  },
  export_svg: {
    type: "coBool",
  },
  exposure_time: {
    type: "coFloat",
    min: 0,
  },
  extruder: {
    type: "coInt",
    min: 0,
  },
  extruder_ams_count: {
    type: "coStrings",
  },
  extruder_clearance_dist_to_rod: {
    type: "coFloat",
    min: 0,
  },
  extruder_clearance_height_to_lid: {
    type: "coFloat",
    min: 0,
  },
  extruder_clearance_height_to_rod: {
    type: "coFloat",
    min: 0,
  },
  extruder_clearance_max_radius: {
    type: "coFloat",
    min: 0,
  },
  extruder_colour: {
    type: "coStrings",
  },
  extruder_max_nozzle_count: {
    type: "coInts",
  },
  extruder_nozzle_count: {
    type: "coInts",
  },
  extruder_nozzle_stats: {
    type: "coStrings",
  },
  extruder_nozzle_stats_new: {
    type: "coStrings",
  },
  extruder_nozzle_volume_type: {
    type: "coEnums",
  },
  extruder_offset: {
    type: "coPoints",
    min: -5,
    max: 5,
  },
  extruder_printable_area: {
    type: "coPointsGroups",
  },
  extruder_printable_height: {
    type: "coFloats",
    min: 0,
    max: 1000,
  },
  extruder_type: {
    type: "coEnums",
    enumValues: ["Direct Drive", "Bowden"],
  },
  extruder_variant_list: {
    type: "coStrings",
  },
  faded_layers: {
    type: "coInt",
    min: 3,
    max: 20,
  },
  fan_cooling_layer_time: {
    type: "coInts",
    min: 0,
    max: 1000,
  },
  fan_direction: {
    type: "coEnum",
    enumValues: ["undefine", "left", "right", "both"],
  },
  fan_max_speed: {
    type: "coInts",
    min: 0,
    max: 100,
  },
  fan_min_speed: {
    type: "coInts",
    min: 0,
    max: 100,
  },
  farthest_point_timelapse: {
    type: "coBool",
  },
  fast_tilt_time: {
    type: "coFloat",
    min: 0,
  },
  filament_adaptive_volumetric_speed: {
    type: "coBools",
  },
  filament_adhesiveness_category: {
    type: "coInts",
    min: 0,
  },
  filament_change_length: {
    type: "coFloats",
    min: 0,
  },
  filament_change_length_nc: {
    type: "coFloats",
    min: 0,
  },
  filament_colour: {
    type: "coStrings",
  },
  filament_colour_type: {
    type: "coStrings",
  },
  filament_cooling_before_tower: {
    type: "coFloats",
  },
  filament_cost: {
    type: "coFloats",
    min: 0,
  },
  filament_density: {
    type: "coFloats",
    min: 0,
  },
  filament_dev_ams_drying_ams_limitations: {
    type: "coStrings",
  },
  filament_dev_ams_drying_heat_distortion_temperature: {
    type: "coFloats",
  },
  filament_dev_ams_drying_temperature: {
    type: "coFloats",
  },
  filament_dev_ams_drying_time: {
    type: "coFloats",
  },
  filament_dev_chamber_drying_bed_temperature: {
    type: "coFloats",
  },
  filament_dev_chamber_drying_time: {
    type: "coFloats",
  },
  filament_dev_drying_cooling_temperature: {
    type: "coFloats",
  },
  filament_dev_drying_softening_temperature: {
    type: "coFloats",
  },
  filament_diameter: {
    type: "coFloats",
    min: 0,
  },
  filament_end_gcode: {
    type: "coStrings",
  },
  filament_extruder_compatibility: {
    type: "coInts",
  },
  filament_extruder_id: {
    type: "coInts",
  },
  filament_extruder_variant: {
    type: "coStrings",
  },
  filament_flow_ratio: {
    type: "coFloats",
    max: 2,
  },
  filament_flush_temp: {
    type: "coInts",
    min: 0,
    max: 1500,
  },
  filament_flush_temp_fast: {
    type: "coInts",
    min: 0,
    max: 1500,
  },
  filament_flush_volumetric_speed: {
    type: "coFloats",
    min: 0,
    max: 200,
  },
  filament_ids: {
    type: "coStrings",
  },
  filament_is_mixed: {
    type: "coBools",
  },
  filament_is_support: {
    type: "coBools",
  },
  filament_map: {
    type: "coInts",
  },
  filament_map_2: {
    type: "coInts",
  },
  filament_map_mode: {
    type: "coEnum",
    enumValues: [
      "Auto For Flush",
      "Auto For Match",
      "Manual",
      "Nozzle Manual",
      "Default",
    ],
  },
  filament_max_volumetric_speed: {
    type: "coFloats",
    min: 0,
    max: 200,
  },
  filament_metal_stickiness: {
    type: "coEnums",
    enumValues: ["None", "Low", "Medium", "High"],
  },
  filament_minimal_purge_on_wipe_tower: {
    type: "coFloats",
    min: 0,
  },
  filament_mixed_components: {
    type: "coStrings",
  },
  filament_mixed_gradient: {
    type: "coBools",
  },
  filament_mixed_gradient_curve: {
    type: "coStrings",
  },
  filament_mixed_gradient_per_part: {
    type: "coBools",
  },
  filament_mixed_gradient_range: {
    type: "coStrings",
  },
  filament_mixed_sublayer_ratios: {
    type: "coStrings",
  },
  filament_multi_colour: {
    type: "coStrings",
  },
  filament_notes: {
    type: "coString",
  },
  filament_nozzle_map: {
    type: "coInts",
  },
  filament_pre_cooling_temperature: {
    type: "coInts",
    min: 0,
    enumValues: ["-1"],
  },
  filament_pre_cooling_temperature_nc: {
    type: "coInts",
    min: 0,
  },
  filament_preheat_temperature_delta: {
    type: "coFloats",
  },
  filament_prime_volume: {
    type: "coFloats",
    min: 1,
  },
  filament_prime_volume_nc: {
    type: "coFloats",
    min: 1,
  },
  filament_printable: {
    type: "coInts",
  },
  filament_ramming_travel_time: {
    type: "coFloats",
    min: 0,
  },
  filament_ramming_travel_time_nc: {
    type: "coFloats",
    min: 0,
  },
  filament_ramming_volumetric_speed: {
    type: "coFloats",
    min: -1,
    max: 200,
  },
  filament_ramming_volumetric_speed_nc: {
    type: "coFloats",
    min: -1,
    max: 200,
  },
  filament_retract_length_nc: {
    type: "coFloats",
    min: 0,
    max: 18,
  },
  filament_scarf_gap: {
    type: "coFloatsOrPercents",
    min: 0,
  },
  filament_scarf_height: {
    type: "coFloatsOrPercents",
    min: 0,
  },
  filament_scarf_length: {
    type: "coFloats",
    min: 0,
  },
  filament_scarf_seam_type: {
    type: "coEnums",
    enumValues: ["none", "external", "all"],
  },
  filament_self_index: {
    type: "coInts",
  },
  filament_settings_id: {
    type: "coStrings",
  },
  filament_shrink: {
    type: "coPercents",
    min: 10,
  },
  filament_soluble: {
    type: "coBools",
  },
  filament_start_gcode: {
    type: "coStrings",
  },
  filament_tower_interface_pre_extrusion_dist: {
    type: "coFloats",
    min: 0,
  },
  filament_tower_interface_pre_extrusion_length: {
    type: "coFloats",
    min: 0,
  },
  filament_tower_interface_print_temp: {
    type: "coInts",
    min: -1,
  },
  filament_tower_interface_purge_volume: {
    type: "coFloats",
    min: 0,
  },
  filament_tower_ironing_area: {
    type: "coFloats",
    min: 0,
  },
  filament_type: {
    type: "coStrings",
    enumValues: [
      "PLA",
      "ABS",
      "ASA",
      "ASA-CF",
      "PETG",
      "PCTG",
      "TPU",
      "TPU-AMS",
      "PC",
      "PA",
      "PA-CF",
      "PA-GF",
      "PA6-CF",
      "PLA-CF",
      "PET-CF",
      "PETG-CF",
      "PVA",
      "HIPS",
      "PLA-AERO",
      "PPS",
      "PPS-CF",
      "PPA-CF",
      "PPA-GF",
      "ABS-GF",
      "ASA-AERO",
      "PE",
      "PP",
      "EVA",
      "PHA",
      "BVOH",
      "PE-CF",
      "PP-CF",
      "PP-GF",
    ],
  },
  filament_velocity_adaptation_factor: {
    type: "coFloats",
    min: 0,
  },
  filament_vendor: {
    type: "coStrings",
  },
  filament_volume_map: {
    type: "coInts",
  },
  filename_format: {
    type: "coString",
  },
  fill_multiline: {
    type: "coInt",
    min: 1,
    max: 5,
  },
  filter_out_gap_fill: {
    type: "coFloat",
  },
  first_layer_print_sequence: {
    type: "coInts",
    min: 0,
    max: 16,
  },
  first_layer_sequence_choice: {
    type: "coEnum",
    enumValues: ["Auto", "Customize"],
  },
  first_x_layer_fan_speed: {
    type: "coFloats",
    min: 0,
    max: 100,
  },
  first_x_layer_part_fan_speed: {
    type: "coInts",
    min: 0,
    max: 100,
  },
  flush_into_infill: {
    type: "coBool",
  },
  flush_into_objects: {
    type: "coBool",
  },
  flush_into_support: {
    type: "coBool",
  },
  flush_multiplier: {
    type: "coFloats",
  },
  flush_multiplier_fast: {
    type: "coFloats",
  },
  flush_volumes_matrix: {
    type: "coFloats",
  },
  flush_volumes_vector: {
    type: "coFloats",
  },
  full_fan_speed_layer: {
    type: "coInts",
    min: 0,
    max: 100000,
  },
  fuzzy_skin: {
    type: "coEnum",
    enumValues: ["none", "external", "all", "allwalls", "disabled_fuzzy"],
  },
  fuzzy_skin_first_layer: {
    type: "coBool",
  },
  fuzzy_skin_mode: {
    type: "coEnum",
    enumValues: ["displacement", "extrusion", "combined"],
  },
  fuzzy_skin_noise_type: {
    type: "coEnum",
    enumValues: ["classic", "perlin", "billow", "ridgedmulti", "voronoi"],
  },
  fuzzy_skin_octaves: {
    type: "coInt",
    min: 1,
    max: 10,
  },
  fuzzy_skin_persistence: {
    type: "coFloat",
    min: 0.01,
    max: 1,
  },
  fuzzy_skin_point_distance: {
    type: "coFloat",
    min: 0,
    max: 5,
  },
  fuzzy_skin_scale: {
    type: "coFloat",
    min: 0.1,
    max: 500,
  },
  fuzzy_skin_thickness: {
    type: "coFloat",
    min: 0,
    max: 1,
  },
  gamma_correction: {
    type: "coFloat",
    min: 0,
    max: 1,
  },
  gap_infill_speed: {
    type: "coFloats",
    min: 0,
  },
  gcode_add_line_number: {
    type: "coBool",
  },
  gcode_flavor: {
    type: "coEnum",
    enumValues: [
      "marlin",
      "klipper",
      "reprap",
      "reprapfirmware",
      "repetier",
      "teacup",
      "makerware",
      "marlin2",
      "sailfish",
      "mach3",
      "machinekit",
      "smoothie",
      "no-extrusion",
    ],
  },
  gcodeviewer: {
    type: "coBool",
  },
  grab_length: {
    type: "coFloats",
    min: 0,
  },
  group_algo_with_time: {
    type: "coBool",
  },
  has_filament_switcher: {
    type: "coBool",
  },
  has_scarf_joint_seam: {
    type: "coBool",
    min: 0,
  },
  head_wrap_detect_zone: {
    type: "coPoints",
  },
  help: {
    type: "coBool",
  },
  help_fff: {
    type: "coBool",
  },
  help_sla: {
    type: "coBool",
  },
  hole_coef_1: {
    type: "coFloats",
  },
  hole_coef_2: {
    type: "coFloats",
  },
  hole_coef_3: {
    type: "coFloats",
  },
  hole_limit_max: {
    type: "coFloats",
  },
  hole_limit_min: {
    type: "coFloats",
  },
  hollowing_closing_distance: {
    type: "coFloat",
    min: 0,
    max: 10,
  },
  hollowing_enable: {
    type: "coBool",
  },
  hollowing_min_thickness: {
    type: "coFloat",
    min: 1,
    max: 10,
  },
  hollowing_quality: {
    type: "coFloat",
    min: 0,
    max: 1,
  },
  host_type: {
    type: "coEnum",
    enumValues: [
      "prusalink",
      "octoprint",
      "duet",
      "flashair",
      "astrobox",
      "repetier",
      "mks",
    ],
  },
  hot_plate_temp: {
    type: "coInts",
    min: 0,
    max: 120,
  },
  hot_plate_temp_initial_layer: {
    type: "coInts",
    min: 0,
    max: 120,
  },
  hotend_cooling_rate: {
    type: "coFloats",
  },
  hotend_heating_rate: {
    type: "coFloats",
  },
  ignore_nonexistent_config: {
    type: "coBool",
  },
  impact_strength_z: {
    type: "coFloats",
  },
  independent_support_layer_height: {
    type: "coBool",
  },
  infill_combination: {
    type: "coBool",
  },
  infill_direction: {
    type: "coFloat",
    min: 0,
    max: 360,
  },
  infill_instead_top_bottom_surfaces: {
    type: "coBool",
  },
  infill_jerk: {
    type: "coFloat",
    min: 0,
  },
  infill_lock_depth: {
    type: "coFloat",
    min: 0,
    max: 100,
  },
  infill_rotate_step: {
    type: "coFloat",
    min: 0,
    max: 360,
  },
  infill_shift_step: {
    type: "coFloat",
    min: 0,
    max: 10,
  },
  infill_wall_overlap: {
    type: "coPercent",
  },
  info: {
    type: "coBool",
  },
  inherits: {
    type: "coString",
  },
  inherits_group: {
    type: "coStrings",
  },
  initial_exposure_time: {
    type: "coFloat",
    min: 0,
  },
  initial_layer_acceleration: {
    type: "coFloats",
    min: 0,
  },
  initial_layer_flow_ratio: {
    type: "coFloat",
    min: 0,
    max: 2,
  },
  initial_layer_height: {
    type: "coFloat",
    min: 0,
  },
  initial_layer_infill_speed: {
    type: "coFloats",
    min: 1,
  },
  initial_layer_jerk: {
    type: "coFloat",
    min: 0,
  },
  initial_layer_line_width: {
    type: "coFloat",
    min: 0,
  },
  initial_layer_print_height: {
    type: "coFloat",
    min: 0,
  },
  initial_layer_speed: {
    type: "coFloats",
    min: 0,
  },
  initial_layer_travel_acceleration: {
    type: "coFloats",
    min: 0,
  },
  inner_wall_acceleration: {
    type: "coFloats",
    min: 0,
  },
  inner_wall_jerk: {
    type: "coFloat",
    min: 0,
  },
  inner_wall_line_width: {
    type: "coFloat",
    min: 0,
  },
  inner_wall_speed: {
    type: "coFloats",
    min: 0,
  },
  interface_shells: {
    type: "coBool",
  },
  interlocking_beam: {
    type: "coBool",
  },
  interlocking_beam_layer_count: {
    type: "coInt",
    min: 1,
  },
  interlocking_beam_width: {
    type: "coFloat",
    min: 0.01,
  },
  interlocking_boundary_avoidance: {
    type: "coInt",
    min: 0,
  },
  interlocking_depth: {
    type: "coInt",
    min: 1,
  },
  interlocking_orientation: {
    type: "coFloat",
    min: 0,
    max: 360,
  },
  internal_bridge_support_thickness: {
    type: "coFloat",
    min: 0,
    max: 2,
  },
  internal_solid_infill_line_width: {
    type: "coFloat",
    min: 0,
  },
  internal_solid_infill_pattern: {
    type: "coEnum",
  },
  internal_solid_infill_speed: {
    type: "coFloats",
    min: 0,
  },
  ironing_direction: {
    type: "coFloat",
    min: 0,
    max: 360,
  },
  ironing_fan_speed: {
    type: "coInts",
    min: -1,
    max: 100,
  },
  ironing_flow: {
    type: "coPercent",
    min: 0,
    max: 100,
  },
  ironing_inset: {
    type: "coFloat",
    min: 0,
    max: 100,
  },
  ironing_pattern: {
    type: "coEnum",
    enumValues: ["concentric", "zig-zag"],
  },
  ironing_spacing: {
    type: "coFloat",
    min: 0,
    max: 1,
  },
  ironing_speed: {
    type: "coFloat",
    min: 0,
  },
  ironing_type: {
    type: "coEnum",
    enumValues: ["no ironing", "top", "topmost", "solid"],
  },
  is_infill_first: {
    type: "coBool",
  },
  layer_change_gcode: {
    type: "coString",
  },
  layer_height: {
    type: "coFloat",
    min: 0,
  },
  line_width: {
    type: "coFloat",
    min: 0,
    max: 10,
  },
  load: {
    type: "coStrings",
  },
  load_assemble_list: {
    type: "coString",
  },
  load_custom_gcodes: {
    type: "coString",
  },
  load_defaultfila: {
    type: "coBool",
  },
  load_filament_ids: {
    type: "coInts",
  },
  load_filaments: {
    type: "coStrings",
  },
  load_settings: {
    type: "coStrings",
  },
  load_slicedata: {
    type: "coStrings",
  },
  locked_skeleton_infill_pattern: {
    type: "coEnum",
    enumValues: [
      "concentric",
      "zig-zag",
      "grid",
      "line",
      "cubic",
      "triangles",
      "tri-hexagon",
      "gyroid",
      "honeycomb",
      "alignedrectilinear",
      "3dhoneycomb",
      "hilbertcurve",
      "archimedeanchords",
      "octagramspiral",
      "crosshatch",
      "zigzag",
      "crosszag",
    ],
  },
  locked_skin_infill_pattern: {
    type: "coEnum",
    enumValues: [
      "concentric",
      "zig-zag",
      "grid",
      "line",
      "cubic",
      "triangles",
      "tri-hexagon",
      "gyroid",
      "honeycomb",
      "alignedrectilinear",
      "3dhoneycomb",
      "hilbertcurve",
      "archimedeanchords",
      "octagramspiral",
      "crosshatch",
      "zigzag",
      "crosszag",
    ],
  },
  long_retractions_when_cut: {
    type: "coBools",
  },
  long_retractions_when_ec: {
    type: "coBools",
  },
  machine_bed_mass_Y: {
    type: "coFloat",
    min: 0,
  },
  machine_end_gcode: {
    type: "coString",
  },
  machine_hotend_change_time: {
    type: "coFloat",
    min: 0,
  },
  machine_load_filament_time: {
    type: "coFloat",
    min: 0,
  },
  machine_max_acceleration_extruding: {
    type: "coFloats",
    min: 0,
  },
  machine_max_acceleration_retracting: {
    type: "coFloats",
    min: 0,
  },
  machine_max_acceleration_travel: {
    type: "coFloats",
    min: 0,
  },
  machine_max_force_Y: {
    type: "coFloat",
    min: 0,
  },
  machine_max_printed_mass: {
    type: "coFloat",
    min: 0,
  },
  machine_min_extruding_rate: {
    type: "coFloats",
    min: 0,
  },
  machine_min_travel_rate: {
    type: "coFloats",
    min: 0,
  },
  machine_pause_gcode: {
    type: "coString",
  },
  machine_prepare_compensation_time: {
    type: "coFloat",
  },
  machine_start_gcode: {
    type: "coString",
  },
  machine_switch_extruder_time: {
    type: "coFloat",
    min: 0,
  },
  machine_unload_filament_time: {
    type: "coFloat",
    min: 0,
  },
  makerlab_name: {
    type: "coString",
  },
  makerlab_version: {
    type: "coString",
  },
  master_extruder_id: {
    type: "coInt",
  },
  material_colour: {
    type: "coString",
  },
  material_correction: {
    type: "coFloats",
    min: 0,
  },
  material_correction_x: {
    type: "coFloat",
    min: 0,
  },
  material_correction_y: {
    type: "coFloat",
    min: 0,
  },
  material_correction_z: {
    type: "coFloat",
    min: 0,
  },
  material_density: {
    type: "coFloat",
    min: 0,
  },
  material_print_speed: {
    type: "coEnum",
    enumValues: ["slow", "fast"],
  },
  material_type: {
    type: "coString",
    enumValues: ["Tough", "Flexible", "Casting", "Dental", "Heat-resistant"],
  },
  material_vendor: {
    type: "coString",
  },
  max_bridge_length: {
    type: "coFloat",
    min: 0,
  },
  max_exposure_time: {
    type: "coFloat",
    min: 0,
  },
  max_initial_exposure_time: {
    type: "coFloat",
    min: 0,
  },
  max_layer_height: {
    type: "coFloats",
    min: 0,
  },
  max_travel_detour_distance: {
    type: "coFloatOrPercent",
    min: 0,
  },
  max_volumetric_extrusion_rate_slope_negative: {
    type: "coFloat",
    min: 0,
  },
  max_volumetric_extrusion_rate_slope_positive: {
    type: "coFloat",
    min: 0,
  },
  metadata_name: {
    type: "coStrings",
  },
  metadata_value: {
    type: "coStrings",
  },
  min_bead_width: {
    type: "coPercent",
    min: 0,
  },
  min_exposure_time: {
    type: "coFloat",
    min: 0,
  },
  min_feature_size: {
    type: "coPercent",
    min: 0,
  },
  min_initial_exposure_time: {
    type: "coFloat",
    min: 0,
  },
  min_layer_height: {
    type: "coFloats",
    min: 0,
  },
  min_save: {
    type: "coBool",
  },
  minimum_sparse_infill_area: {
    type: "coFloat",
    min: 0,
  },
  mmu_segmented_region_interlocking_depth: {
    type: "coFloat",
    min: 0,
  },
  mmu_segmented_region_max_width: {
    type: "coFloat",
    min: 0,
  },
  monotonic_travel_into_wall: {
    type: "coPercent",
    min: 0,
    max: 200,
  },
  mstpp: {
    type: "coInt",
  },
  mtcpp: {
    type: "coInt",
  },
  no_check: {
    type: "coBool",
  },
  no_slow_down_for_cooling_on_outwalls: {
    type: "coBools",
  },
  normative_check: {
    type: "coBool",
  },
  nozzle_diameter: {
    type: "coFloats",
    max: 1,
  },
  nozzle_flush_dataset: {
    type: "coInts",
  },
  nozzle_height: {
    type: "coFloat",
    min: 0,
  },
  nozzle_temperature: {
    type: "coInts",
    min: 0,
    max: 1500,
  },
  nozzle_temperature_initial_layer: {
    type: "coInts",
    min: 0,
    max: 1500,
  },
  nozzle_temperature_range_high: {
    type: "coInts",
    min: 0,
    max: 1500,
  },
  nozzle_temperature_range_low: {
    type: "coInts",
    min: 0,
    max: 1500,
  },
  nozzle_type: {
    type: "coEnums",
    enumValues: [
      "undefine",
      "hardened_steel",
      "stainless_steel",
      "tungsten_carbide",
      "brass",
    ],
  },
  nozzle_volume: {
    type: "coFloats",
  },
  nozzle_volume_type: {
    type: "coEnums",
  },
  only_one_wall_first_layer: {
    type: "coBool",
  },
  ooze_prevention: {
    type: "coBool",
  },
  orient: {
    type: "coInt",
  },
  other_layers_print_sequence: {
    type: "coInts",
    min: 0,
    max: 16,
  },
  other_layers_print_sequence_nums: {
    type: "coInt",
  },
  other_layers_sequence_choice: {
    type: "coEnum",
    enumValues: ["Auto", "Customize"],
  },
  outer_wall_acceleration: {
    type: "coFloats",
    min: 0,
  },
  outer_wall_jerk: {
    type: "coFloat",
    min: 0,
  },
  outer_wall_line_width: {
    type: "coFloat",
    min: 0,
  },
  outer_wall_speed: {
    type: "coFloats",
    min: 0,
  },
  output: {
    type: "coString",
  },
  outputdir: {
    type: "coString",
  },
  overhang_1_4_speed: {
    type: "coFloats",
    min: 0,
  },
  overhang_2_4_speed: {
    type: "coFloats",
    min: 0,
  },
  overhang_3_4_speed: {
    type: "coFloats",
    min: 0,
  },
  overhang_4_4_speed: {
    type: "coFloats",
    min: 0,
  },
  overhang_fan_speed: {
    type: "coInts",
    min: 0,
    max: 100,
  },
  overhang_fan_threshold: {
    type: "coEnums",
    enumValues: ["0%", "10%", "25%", "50%", "75%", "95%"],
  },
  overhang_threshold_participating_cooling: {
    type: "coEnums",
    enumValues: ["0%", "10%", "25%", "50%", "75%", "100%"],
  },
  overhang_totally_speed: {
    type: "coFloats",
    min: 0,
  },
  override_filament_scarf_seam_setting: {
    type: "coBool",
  },
  override_process_overhang_speed: {
    type: "coBools",
  },
  pad_around_object: {
    type: "coBool",
  },
  pad_around_object_everywhere: {
    type: "coBool",
  },
  pad_brim_size: {
    type: "coFloat",
    min: 0,
    max: 30,
  },
  pad_enable: {
    type: "coBool",
  },
  pad_max_merge_distance: {
    type: "coFloat",
    min: 0,
  },
  pad_object_connector_penetration: {
    type: "coFloat",
    min: 0,
  },
  pad_object_connector_stride: {
    type: "coFloat",
    min: 0,
  },
  pad_object_connector_width: {
    type: "coFloat",
    min: 0,
  },
  pad_object_gap: {
    type: "coFloat",
    min: 0,
    max: 10,
  },
  pad_wall_height: {
    type: "coFloat",
    min: 0,
    max: 30,
  },
  pad_wall_slope: {
    type: "coFloat",
    min: 45,
    max: 90,
  },
  pad_wall_thickness: {
    type: "coFloat",
    min: 0,
    max: 30,
  },
  physical_extruder_map: {
    type: "coInts",
  },
  pipe: {
    type: "coString",
  },
  post_process: {
    type: "coStrings",
  },
  pre_start_fan_time: {
    type: "coFloats",
    min: 0,
    max: 5,
  },
  precise_outer_wall: {
    type: "coBool",
  },
  precise_z_height: {
    type: "coBool",
  },
  preset_name: {
    type: "coString",
  },
  preset_names: {
    type: "coStrings",
  },
  pressure_advance: {
    type: "coFloats",
    max: 2,
  },
  prime_tower_brim_width: {
    type: "coFloat",
    min: -1,
    enumValues: ["-1"],
  },
  prime_tower_enable_framework: {
    type: "coBool",
  },
  prime_tower_extra_rib_length: {
    type: "coFloat",
    max: 300,
  },
  prime_tower_fillet_wall: {
    type: "coBool",
  },
  prime_tower_flat_ironing: {
    type: "coBool",
  },
  prime_tower_infill_gap: {
    type: "coPercent",
    min: 100,
  },
  prime_tower_lift_height: {
    type: "coFloat",
  },
  prime_tower_lift_speed: {
    type: "coFloat",
  },
  prime_tower_max_speed: {
    type: "coFloat",
    min: 10,
  },
  prime_tower_rib_wall: {
    type: "coBool",
  },
  prime_tower_rib_width: {
    type: "coFloat",
    min: 0,
    max: 300,
  },
  prime_tower_skip_points: {
    type: "coBool",
  },
  prime_tower_width: {
    type: "coFloat",
    min: 2,
  },
  prime_volume: {
    type: "coFloat",
    min: 1,
  },
  prime_volume_mode: {
    type: "coEnum",
    enumValues: ["Default", "Saving", "Fast"],
  },
  print_compatible_printers: {
    type: "coStrings",
  },
  print_extruder_id: {
    type: "coInts",
  },
  print_extruder_variant: {
    type: "coStrings",
  },
  print_flow_ratio: {
    type: "coFloat",
    min: 0.01,
    max: 2,
  },
  print_host: {
    type: "coString",
  },
  print_host_webui: {
    type: "coString",
  },
  print_in_clockwise: {
    type: "coBool",
  },
  print_sequence: {
    type: "coEnum",
    enumValues: ["by layer", "by object"],
  },
  print_settings_id: {
    type: "coString",
  },
  printable_area: {
    type: "coPoints",
  },
  printable_height: {
    type: "coFloat",
    min: 0,
    max: 1000,
  },
  printer_extruder_id: {
    type: "coInts",
  },
  printer_extruder_variant: {
    type: "coStrings",
  },
  printer_model: {
    type: "coString",
  },
  printer_notes: {
    type: "coString",
  },
  printer_settings_id: {
    type: "coString",
  },
  printer_structure: {
    type: "coEnum",
    enumValues: ["undefine", "corexy", "i3", "hbot", "delta"],
  },
  printer_technology: {
    type: "coEnum",
    enumValues: ["FFF", "SLA"],
  },
  printer_variant: {
    type: "coString",
  },
  printhost_apikey: {
    type: "coString",
  },
  printhost_authorization_type: {
    type: "coEnum",
    enumValues: ["key", "user"],
  },
  printhost_cafile: {
    type: "coString",
  },
  printhost_password: {
    type: "coString",
  },
  printhost_port: {
    type: "coString",
  },
  printhost_ssl_ignore_revoke: {
    type: "coBool",
  },
  printhost_user: {
    type: "coString",
  },
  printing_by_object_gcode: {
    type: "coString",
  },
  process_notes: {
    type: "coString",
  },
  raft_contact_distance: {
    type: "coFloat",
    min: 0,
  },
  raft_expansion: {
    type: "coFloat",
    min: 0,
  },
  raft_first_layer_density: {
    type: "coPercent",
    min: 10,
    max: 100,
  },
  raft_first_layer_expansion: {
    type: "coFloat",
    min: -1,
  },
  raft_layers: {
    type: "coInt",
    min: 0,
    max: 100,
  },
  reduce_crossing_wall: {
    type: "coBool",
  },
  reduce_fan_stop_start_freq: {
    type: "coBools",
  },
  reduce_infill_retraction_mode: {
    type: "coEnum",
    enumValues: ["Disabled", "Auto", "Enabled"],
  },
  relative_correction: {
    type: "coFloats",
    min: 0,
  },
  relative_correction_x: {
    type: "coFloat",
    min: 0,
  },
  relative_correction_y: {
    type: "coFloat",
    min: 0,
  },
  relative_correction_z: {
    type: "coFloat",
    min: 0,
  },
  repair: {
    type: "coBool",
  },
  repetitions: {
    type: "coInt",
  },
  required_nozzle_HRC: {
    type: "coInts",
    min: 0,
    max: 500,
  },
  resolution: {
    type: "coFloat",
    min: 0,
  },
  retract_before_wipe: {
    type: "coPercents",
  },
  retract_length_toolchange: {
    type: "coFloats",
  },
  retract_lift_above: {
    type: "coFloats",
    min: 0,
  },
  retract_lift_below: {
    type: "coFloats",
    min: 0,
  },
  retract_restart_extra: {
    type: "coFloats",
  },
  retract_restart_extra_toolchange: {
    type: "coFloats",
  },
  retract_when_changing_layer: {
    type: "coBools",
  },
  retraction_distances_when_cut: {
    type: "coFloats",
    min: 10,
    max: 18,
  },
  retraction_distances_when_ec: {
    type: "coFloats",
    min: 0,
    max: 10,
  },
  retraction_length: {
    type: "coFloats",
  },
  retraction_minimum_travel: {
    type: "coFloats",
  },
  retraction_speed: {
    type: "coFloats",
  },
  role_base_wipe_speed: {
    type: "coBool",
  },
  rotate: {
    type: "coFloat",
  },
  rotate_x: {
    type: "coFloat",
  },
  rotate_y: {
    type: "coFloat",
  },
  scale: {
    type: "coFloat",
  },
  scale_to_fit: {
    type: "coPoint3",
  },
  scan_first_layer: {
    type: "coBool",
  },
  scarf_angle_threshold: {
    type: "coInt",
    min: 0,
    max: 180,
  },
  seam_gap: {
    type: "coPercent",
    min: 0,
  },
  seam_placement_away_from_overhangs: {
    type: "coBool",
  },
  seam_position: {
    type: "coEnum",
    enumValues: ["nearest", "aligned", "back", "random"],
  },
  seam_slope_conditional: {
    type: "coBool",
  },
  seam_slope_entire_loop: {
    type: "coBool",
  },
  seam_slope_gap: {
    type: "coFloatOrPercent",
    min: 0,
  },
  seam_slope_inner_walls: {
    type: "coBool",
  },
  seam_slope_min_length: {
    type: "coFloat",
    min: 0,
  },
  seam_slope_start_height: {
    type: "coFloatOrPercent",
    min: 0,
  },
  seam_slope_steps: {
    type: "coInt",
    min: 1,
  },
  seam_slope_type: {
    type: "coEnum",
    enumValues: ["none", "external", "all"],
  },
  silent_mode: {
    type: "coBool",
  },
  single_extruder_multi_material: {
    type: "coBool",
  },
  single_instance: {
    type: "coBool",
  },
  skeleton_infill_density: {
    type: "coPercent",
    min: 0,
    max: 100,
  },
  skeleton_infill_line_width: {
    type: "coFloat",
    min: 0,
  },
  skin_infill_density: {
    type: "coPercent",
    min: 0,
    max: 100,
  },
  skin_infill_depth: {
    type: "coFloat",
    min: 0,
    max: 100,
  },
  skin_infill_line_width: {
    type: "coFloat",
    min: 0,
  },
  skip_modified_gcodes: {
    type: "coBool",
  },
  skip_objects: {
    type: "coInts",
  },
  skip_useless_pick: {
    type: "coBool",
  },
  skirt_distance: {
    type: "coFloat",
    min: 0,
    max: 55,
  },
  skirt_height: {
    type: "coInt",
    max: 10000,
  },
  skirt_loops: {
    type: "coInt",
    min: 0,
    max: 10,
  },
  skirt_per_object: {
    type: "coBool",
  },
  sla_material_settings_id: {
    type: "coString",
  },
  sla_print_settings_id: {
    type: "coString",
  },
  slice: {
    type: "coInt",
  },
  slice_closing_radius: {
    type: "coFloat",
    min: 0,
  },
  slicing_mode: {
    type: "coEnum",
    enumValues: ["regular", "even_odd", "close_holes"],
  },
  slow_down_for_layer_cooling: {
    type: "coBools",
  },
  slow_down_layer_time: {
    type: "coInts",
    min: 0,
    max: 1000,
  },
  slow_down_min_speed: {
    type: "coFloats",
    min: 0,
  },
  slow_tilt_time: {
    type: "coFloat",
    min: 0,
  },
  slowdown_end_acc: {
    type: "coFloats",
    min: 0,
  },
  slowdown_end_height: {
    type: "coFloats",
    min: 0,
  },
  slowdown_end_speed: {
    type: "coFloats",
    min: 0,
  },
  slowdown_start_acc: {
    type: "coFloats",
    min: 0,
  },
  slowdown_start_height: {
    type: "coFloats",
    min: 0,
  },
  slowdown_start_speed: {
    type: "coFloats",
    min: 0,
  },
  small_perimeter_speed: {
    type: "coFloatsOrPercents",
    min: 0,
  },
  small_perimeter_threshold: {
    type: "coFloats",
    min: 0,
  },
  smooth_coefficient: {
    type: "coFloat",
    min: 0,
  },
  smooth_speed_discontinuity_area: {
    type: "coBool",
  },
  solid_infill_filament: {
    type: "coInt",
    min: 0,
  },
  spaghetti_detector: {
    type: "coBool",
  },
  sparse_infill_acceleration: {
    type: "coFloatsOrPercents",
    min: 0,
  },
  sparse_infill_anchor: {
    type: "coFloatOrPercent",
    enumValues: ["0", "1", "2", "5", "10", "1000"],
  },
  sparse_infill_anchor_max: {
    type: "coFloatOrPercent",
    enumValues: ["0", "1", "2", "5", "10", "1000"],
  },
  sparse_infill_density: {
    type: "coPercent",
    min: 0,
    max: 100,
  },
  sparse_infill_filament: {
    type: "coInt",
    min: 0,
  },
  sparse_infill_lattice_angle_1: {
    type: "coFloat",
    min: -75,
    max: 75,
  },
  sparse_infill_lattice_angle_2: {
    type: "coFloat",
    min: -75,
    max: 75,
  },
  sparse_infill_line_width: {
    type: "coFloat",
    min: 0,
  },
  sparse_infill_pattern: {
    type: "coEnum",
    enumValues: [
      "concentric",
      "zig-zag",
      "grid",
      "line",
      "cubic",
      "triangles",
      "tri-hexagon",
      "gyroid",
      "honeycomb",
      "adaptivecubic",
      "alignedrectilinear",
      "3dhoneycomb",
      "hilbertcurve",
      "archimedeanchords",
      "octagramspiral",
      "supportcubic",
      "lightning",
      "crosshatch",
      "zigzag",
      "crosszag",
      "lockedzag",
      "2dlattice",
    ],
  },
  sparse_infill_speed: {
    type: "coFloats",
    min: 0,
  },
  spiral_mode: {
    type: "coBool",
  },
  spiral_mode_max_xy_smoothing: {
    type: "coFloatOrPercent",
    min: 0,
    max: 1000,
  },
  spiral_mode_smooth: {
    type: "coBool",
  },
  split: {
    type: "coBool",
  },
  standby_temperature_delta: {
    type: "coInt",
    max: 1500,
  },
  start_end_points: {
    type: "coPoints",
  },
  supertack_plate_temp: {
    type: "coInts",
    min: 0,
    max: 120,
  },
  supertack_plate_temp_initial_layer: {
    type: "coInts",
    min: 0,
    max: 120,
  },
  support_air_filtration: {
    type: "coBool",
  },
  support_angle: {
    type: "coFloat",
    min: 0,
    max: 359,
  },
  support_base_diameter: {
    type: "coFloat",
    min: 0,
    max: 30,
  },
  support_base_height: {
    type: "coFloat",
    min: 0,
  },
  support_base_pattern: {
    type: "coEnum",
    enumValues: [
      "default",
      "rectilinear",
      "rectilinear-grid",
      "honeycomb",
      "lightning",
      "hollow",
    ],
  },
  support_base_pattern_spacing: {
    type: "coFloat",
    min: 0,
  },
  support_base_safety_distance: {
    type: "coFloat",
    min: 0,
    max: 10,
  },
  support_bottom_interface_spacing: {
    type: "coFloat",
    min: 0,
  },
  support_bottom_z_distance: {
    type: "coFloat",
  },
  support_buildplate_only: {
    type: "coBool",
  },
  support_chamber_temp_control: {
    type: "coBool",
  },
  support_cooling_filter: {
    type: "coBool",
  },
  support_critical_angle: {
    type: "coFloat",
    min: 0,
    max: 90,
  },
  support_critical_regions_only: {
    type: "coBool",
  },
  support_expansion: {
    type: "coFloat",
  },
  support_fast_purge_mode: {
    type: "coBool",
  },
  support_filament: {
    type: "coInt",
    min: 0,
  },
  support_head_front_diameter: {
    type: "coFloat",
    min: 0,
  },
  support_head_penetration: {
    type: "coFloat",
    min: 0,
  },
  support_head_width: {
    type: "coFloat",
    min: 0,
    max: 20,
  },
  support_interface_bottom_layers: {
    type: "coInt",
    min: -1,
    enumValues: ["-1"],
  },
  support_interface_filament: {
    type: "coInt",
    min: 0,
  },
  support_interface_loop_pattern: {
    type: "coBool",
  },
  support_interface_not_for_body: {
    type: "coBool",
  },
  support_interface_pattern: {
    type: "coEnum",
    enumValues: [
      "auto",
      "rectilinear",
      "concentric",
      "rectilinear_interlaced",
      "grid",
    ],
  },
  support_interface_spacing: {
    type: "coFloat",
    min: 0,
  },
  support_interface_speed: {
    type: "coFloats",
    min: 1,
  },
  support_interface_top_layers: {
    type: "coInt",
    min: 0,
    enumValues: ["0", "1", "2", "3"],
  },
  support_ironing_direction: {
    type: "coFloat",
    min: 0,
    max: 360,
  },
  support_ironing_flow: {
    type: "coPercent",
    min: 0,
    max: 100,
  },
  support_ironing_inset: {
    type: "coFloat",
    min: 0,
    max: 100,
  },
  support_ironing_pattern: {
    type: "coEnum",
    enumValues: ["concentric", "zig-zag"],
  },
  support_ironing_spacing: {
    type: "coFloat",
    min: 0,
    max: 1,
  },
  support_ironing_speed: {
    type: "coFloat",
    min: 0,
  },
  support_line_width: {
    type: "coFloat",
    min: 0,
  },
  support_max_bridge_length: {
    type: "coFloat",
    min: 0,
  },
  support_max_bridges_on_pillar: {
    type: "coInt",
    min: 0,
    max: 50,
  },
  support_max_pillar_link_distance: {
    type: "coFloat",
    min: 0,
  },
  support_object_elevation: {
    type: "coFloat",
    min: 0,
    max: 150,
  },
  support_object_first_layer_gap: {
    type: "coFloat",
    min: 0,
    max: 10,
  },
  support_object_skip_flush: {
    type: "coBool",
  },
  support_object_xy_distance: {
    type: "coFloat",
    min: 0,
    max: 10,
  },
  support_on_build_plate_only: {
    type: "coBool",
  },
  support_pillar_connection_mode: {
    type: "coEnum",
    enumValues: ["zigzag", "cross", "dynamic"],
  },
  support_pillar_diameter: {
    type: "coFloat",
    min: 0,
    max: 15,
  },
  support_pillar_widening_factor: {
    type: "coFloat",
    min: 0,
    max: 1,
  },
  support_points_density_relative: {
    type: "coInt",
    min: 0,
  },
  support_points_minimal_distance: {
    type: "coFloat",
    min: 0,
  },
  support_remove_small_overhang: {
    type: "coBool",
  },
  support_small_pillar_diameter_percent: {
    type: "coPercent",
    min: 1,
    max: 100,
  },
  support_speed: {
    type: "coFloats",
    min: 0,
  },
  support_style: {
    type: "coEnum",
    enumValues: [
      "default",
      "grid",
      "snug",
      "tree_slim",
      "tree_strong",
      "tree_hybrid",
      "tree_organic",
    ],
  },
  support_threshold_angle: {
    type: "coInt",
    min: 1,
    max: 90,
  },
  support_top_z_distance: {
    type: "coFloat",
    min: 0,
    enumValues: ["0", "0.1", "0.2"],
  },
  support_type: {
    type: "coEnum",
    enumValues: [
      "normal(auto)",
      "tree(auto)",
      "normal(manual)",
      "tree(manual)",
    ],
  },
  supports_enable: {
    type: "coBool",
  },
  sw_renderer: {
    type: "coBool",
    min: 0,
  },
  symmetric_infill_y_axis: {
    type: "coBool",
  },
  temperature_vitrification: {
    type: "coInts",
  },
  template_custom_gcode: {
    type: "coString",
  },
  textured_plate_temp: {
    type: "coInts",
    min: 0,
    max: 120,
  },
  textured_plate_temp_initial_layer: {
    type: "coInts",
    min: 0,
    max: 120,
  },
  thick_bridges: {
    type: "coBool",
  },
  thumbnail_size: {
    type: "coPoints",
  },
  time_lapse_gcode: {
    type: "coString",
  },
  timelapse_type: {
    type: "coEnum",
    enumValues: ["0", "1"],
  },
  top_area_threshold: {
    type: "coPercent",
    min: 0,
    max: 500,
  },
  top_color_penetration_layers: {
    type: "coInt",
    min: 1,
  },
  top_one_wall_type: {
    type: "coEnum",
    enumValues: ["not apply", "all top", "topmost"],
  },
  top_shell_layers: {
    type: "coInt",
    min: 0,
  },
  top_shell_thickness: {
    type: "coFloat",
    min: 0,
  },
  top_solid_infill_flow_ratio: {
    type: "coFloats",
    min: 0,
    max: 2,
  },
  top_surface_acceleration: {
    type: "coFloats",
    min: 0,
  },
  top_surface_density: {
    type: "coPercent",
    min: 0,
    max: 100,
  },
  top_surface_jerk: {
    type: "coFloat",
    min: 0,
  },
  top_surface_line_width: {
    type: "coFloat",
    min: 0,
  },
  top_surface_pattern: {
    type: "coEnum",
    enumValues: [
      "concentric",
      "zig-zag",
      "monotonic",
      "monotonicline",
      "alignedrectilinear",
      "hilbertcurve",
      "archimedeanchords",
      "octagramspiral",
    ],
  },
  top_surface_speed: {
    type: "coFloats",
    min: 0,
  },
  top_z_overrides_xy_distance: {
    type: "coBool",
  },
  travel_acceleration: {
    type: "coFloats",
    min: 0,
  },
  travel_jerk: {
    type: "coFloat",
    min: 0,
  },
  travel_short_distance_acceleration: {
    type: "coFloats",
    min: 0,
  },
  travel_speed: {
    type: "coFloats",
    min: 1,
  },
  travel_speed_z: {
    type: "coFloats",
    min: 0,
  },
  tree_support_branch_angle: {
    type: "coFloat",
    min: 0,
    max: 60,
  },
  tree_support_branch_diameter: {
    type: "coFloat",
    min: 1,
    max: 10,
  },
  tree_support_branch_diameter_angle: {
    type: "coFloat",
    min: 0,
    max: 15,
  },
  tree_support_branch_distance: {
    type: "coFloat",
    min: 1,
    max: 10,
  },
  tree_support_wall_count: {
    type: "coInt",
    min: -1,
    max: 2,
  },
  uptodate: {
    type: "coBool",
  },
  uptodate_filaments: {
    type: "coStrings",
  },
  uptodate_settings: {
    type: "coStrings",
  },
  upward_compatible_machine: {
    type: "coStrings",
  },
  use_firmware_retraction: {
    type: "coBool",
  },
  use_relative_e_distances: {
    type: "coBool",
  },
  vertical_shell_speed: {
    type: "coFloatsOrPercents",
    min: 0,
  },
  volumetric_speed_coefficients: {
    type: "coStrings",
  },
  wall_distribution_count: {
    type: "coInt",
    min: 1,
  },
  wall_filament: {
    type: "coInt",
    min: 0,
  },
  wall_generator: {
    type: "coEnum",
    enumValues: ["classic", "arachne"],
  },
  wall_loops: {
    type: "coInt",
    min: 0,
    max: 1000,
  },
  wall_sequence: {
    type: "coEnum",
    enumValues: [
      "inner wall/outer wall",
      "outer wall/inner wall",
      "inner-outer-inner wall",
    ],
  },
  wall_transition_angle: {
    type: "coFloat",
    min: 1,
    max: 59,
  },
  wall_transition_filter_deviation: {
    type: "coPercent",
    min: 0,
  },
  wall_transition_length: {
    type: "coPercent",
    min: 0,
  },
  wipe: {
    type: "coBools",
  },
  wipe_distance: {
    type: "coFloats",
    min: 0,
  },
  wipe_speed: {
    type: "coPercent",
    min: 0.01,
  },
  wipe_tower_bridging: {
    type: "coFloat",
  },
  wipe_tower_no_sparse_layers: {
    type: "coBool",
  },
  wipe_tower_rotation_angle: {
    type: "coFloat",
  },
  wipe_tower_x: {
    type: "coFloats",
  },
  wipe_tower_y: {
    type: "coFloats",
  },
  wrapping_detection_gcode: {
    type: "coString",
  },
  wrapping_detection_layers: {
    type: "coInt",
    min: 0,
  },
  wrapping_exclude_area: {
    type: "coPoints",
  },
  xy_contour_compensation: {
    type: "coFloat",
  },
  xy_hole_compensation: {
    type: "coFloat",
  },
  z_direction_outwall_speed_continuous: {
    type: "coBool",
  },
  z_hop: {
    type: "coFloats",
    min: 0,
    max: 5,
  },
  z_hop_types: {
    type: "coEnums",
    enumValues: ["Auto Lift", "Normal Lift", "Slope Lift", "Spiral Lift"],
  },
};
