/* eslint-disable */
/**
 * Generated by scripts/generate-profile-validation-data.mjs.
 * Source: ~/Documents/BambuStudio; do not edit manually.
 */
export const PROFILE_VALUE_VALIDATION = {
  "process": {
    "fileCount": 276,
    "knownKeys": [
      "adaptive_layer_height",
      "avoid_crossing_wall_includes_support",
      "bottom_color_penetration_layers",
      "bottom_shell_layers",
      "bottom_shell_thickness",
      "bottom_surface_density",
      "bottom_surface_pattern",
      "bridge_flow",
      "bridge_no_support",
      "bridge_speed",
      "brim_object_gap",
      "brim_width",
      "circle_compensation_manual_offset",
      "compatible_printers",
      "compatible_printers_condition",
      "default_acceleration",
      "description",
      "detect_floating_vertical_shell",
      "detect_overhang_wall",
      "detect_thin_wall",
      "draft_shield",
      "elefant_foot_compensation",
      "enable_arc_fitting",
      "enable_circle_compensation",
      "enable_height_slowdown",
      "enable_overhang_speed",
      "enable_prime_tower",
      "enable_support",
      "enable_support_ironing",
      "enable_tower_interface_features",
      "enable_wrapping_detection",
      "filename_format",
      "fill_multiline",
      "from",
      "fuzzy_skin",
      "fuzzy_skin_first_layer",
      "fuzzy_skin_mode",
      "fuzzy_skin_noise_type",
      "fuzzy_skin_octaves",
      "fuzzy_skin_persistence",
      "fuzzy_skin_point_distance",
      "fuzzy_skin_scale",
      "fuzzy_skin_thickness",
      "gap_infill_speed",
      "infill_combination",
      "infill_direction",
      "infill_instead_top_bottom_surfaces",
      "infill_lock_depth",
      "infill_rotate_step",
      "infill_shift_step",
      "infill_wall_overlap",
      "inherits",
      "initial_layer_acceleration",
      "initial_layer_infill_speed",
      "initial_layer_line_width",
      "initial_layer_print_height",
      "initial_layer_speed",
      "initial_layer_travel_acceleration",
      "inner_wall_acceleration",
      "inner_wall_line_width",
      "inner_wall_speed",
      "instantiation",
      "interface_shells",
      "internal_bridge_support_thickness",
      "internal_solid_infill_line_width",
      "internal_solid_infill_speed",
      "ironing_flow",
      "ironing_inset",
      "ironing_spacing",
      "ironing_speed",
      "ironing_type",
      "layer_height",
      "layer_time_smoothing",
      "layer_time_smoothing_threshold",
      "line_width",
      "locked_skeleton_infill_pattern",
      "locked_skin_infill_pattern",
      "max_bridge_length",
      "max_travel_detour_distance",
      "minimum_sparse_infill_area",
      "monotonic_travel_into_wall",
      "name",
      "only_one_wall_top",
      "outer_wall_acceleration",
      "outer_wall_line_width",
      "outer_wall_speed",
      "overhang_1_4_speed",
      "overhang_2_4_speed",
      "overhang_3_4_speed",
      "overhang_4_4_speed",
      "overhang_totally_speed",
      "override_filament_scarf_seam_setting",
      "pre_start_fan_time",
      "prime_tower_brim_width",
      "prime_tower_enable_framework",
      "prime_tower_flat_ironing",
      "prime_tower_lift_height",
      "prime_tower_lift_speed",
      "prime_tower_max_speed",
      "prime_tower_width",
      "print_extruder_id",
      "print_extruder_variant",
      "print_sequence",
      "print_settings_id",
      "raft_layers",
      "reduce_crossing_wall",
      "reduce_infill_retraction_mode",
      "resolution",
      "scarf_angle_threshold",
      "seam_placement_away_from_overhangs",
      "seam_position",
      "seam_slope_gap",
      "seam_slope_min_length",
      "seam_slope_start_height",
      "seam_slope_type",
      "setting_id",
      "skeleton_infill_density",
      "skeleton_infill_line_width",
      "skin_infill_density",
      "skin_infill_depth",
      "skin_infill_line_width",
      "skirt_distance",
      "skirt_height",
      "skirt_loops",
      "skirt_per_object",
      "slowdown_end_acc",
      "slowdown_end_height",
      "slowdown_end_speed",
      "slowdown_start_acc",
      "slowdown_start_height",
      "slowdown_start_speed",
      "small_perimeter_speed",
      "small_perimeter_threshold",
      "smooth_coefficient",
      "solid_infill_filament",
      "sparse_infill_acceleration",
      "sparse_infill_density",
      "sparse_infill_filament",
      "sparse_infill_lattice_angle_1",
      "sparse_infill_lattice_angle_2",
      "sparse_infill_line_width",
      "sparse_infill_pattern",
      "sparse_infill_speed",
      "spiral_mode",
      "standby_temperature_delta",
      "support_base_pattern",
      "support_base_pattern_spacing",
      "support_bottom_z_distance",
      "support_expansion",
      "support_filament",
      "support_interface_bottom_layers",
      "support_interface_filament",
      "support_interface_loop_pattern",
      "support_interface_pattern",
      "support_interface_spacing",
      "support_interface_speed",
      "support_interface_top_layers",
      "support_ironing_direction",
      "support_ironing_flow",
      "support_ironing_inset",
      "support_ironing_pattern",
      "support_ironing_spacing",
      "support_ironing_speed",
      "support_line_width",
      "support_object_xy_distance",
      "support_on_build_plate_only",
      "support_speed",
      "support_style",
      "support_threshold_angle",
      "support_top_z_distance",
      "support_type",
      "symmetric_infill_y_axis",
      "top_color_penetration_layers",
      "top_shell_layers",
      "top_shell_thickness",
      "top_solid_infill_flow_ratio",
      "top_surface_acceleration",
      "top_surface_density",
      "top_surface_line_width",
      "top_surface_pattern",
      "top_surface_speed",
      "travel_acceleration",
      "travel_short_distance_acceleration",
      "travel_speed",
      "travel_speed_z",
      "tree_support_branch_angle",
      "tree_support_branch_diameter",
      "tree_support_wall_count",
      "type",
      "vertical_shell_speed",
      "wall_filament",
      "wall_generator",
      "wall_infill_order",
      "wall_loops",
      "wipe_tower_no_sparse_layers",
      "xy_contour_compensation",
      "xy_hole_compensation",
      "z_direction_outwall_speed_continuous"
    ],
    "numericBounds": {
      "adaptive_layer_height": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "avoid_crossing_wall_includes_support": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "bottom_color_penetration_layers": {
        "min": 3,
        "max": 7,
        "samples": 17
      },
      "bottom_shell_layers": {
        "min": 3,
        "max": 7,
        "samples": 23
      },
      "bottom_shell_thickness": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "bottom_surface_density": {
        "min": 100,
        "max": 100,
        "samples": 1
      },
      "bridge_flow": {
        "min": 0.95,
        "max": 1.5,
        "samples": 50
      },
      "bridge_no_support": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "bridge_speed": {
        "min": 25,
        "max": 200,
        "samples": 418
      },
      "brim_object_gap": {
        "min": 0.1,
        "max": 0.1,
        "samples": 1
      },
      "brim_width": {
        "min": 5,
        "max": 5,
        "samples": 1
      },
      "circle_compensation_manual_offset": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "default_acceleration": {
        "min": 1000,
        "max": 10000,
        "samples": 541
      },
      "detect_floating_vertical_shell": {
        "min": 1,
        "max": 1,
        "samples": 1
      },
      "detect_overhang_wall": {
        "min": 1,
        "max": 1,
        "samples": 1
      },
      "detect_thin_wall": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "elefant_foot_compensation": {
        "min": 0,
        "max": 0.15,
        "samples": 136
      },
      "enable_arc_fitting": {
        "min": 0,
        "max": 1,
        "samples": 18
      },
      "enable_circle_compensation": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "enable_height_slowdown": {
        "min": 0,
        "max": 1,
        "samples": 307
      },
      "enable_overhang_speed": {
        "min": 0,
        "max": 1,
        "samples": 295
      },
      "enable_prime_tower": {
        "min": 1,
        "max": 1,
        "samples": 1
      },
      "enable_support": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "enable_support_ironing": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "enable_tower_interface_features": {
        "min": 0,
        "max": 1,
        "samples": 49
      },
      "enable_wrapping_detection": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "fill_multiline": {
        "min": 1,
        "max": 1,
        "samples": 1
      },
      "fuzzy_skin_first_layer": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "fuzzy_skin_octaves": {
        "min": 4,
        "max": 4,
        "samples": 1
      },
      "fuzzy_skin_persistence": {
        "min": 0.5,
        "max": 0.5,
        "samples": 1
      },
      "fuzzy_skin_point_distance": {
        "min": 0.8,
        "max": 0.8,
        "samples": 1
      },
      "fuzzy_skin_scale": {
        "min": 1,
        "max": 1,
        "samples": 1
      },
      "fuzzy_skin_thickness": {
        "min": 0.3,
        "max": 0.3,
        "samples": 1
      },
      "gap_infill_speed": {
        "min": 30,
        "max": 350,
        "samples": 399
      },
      "infill_combination": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "infill_direction": {
        "min": 45,
        "max": 45,
        "samples": 1
      },
      "infill_instead_top_bottom_surfaces": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "infill_lock_depth": {
        "min": 1,
        "max": 1,
        "samples": 1
      },
      "infill_rotate_step": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "infill_shift_step": {
        "min": 0.4,
        "max": 0.4,
        "samples": 1
      },
      "infill_wall_overlap": {
        "min": 15,
        "max": 15,
        "samples": 1
      },
      "initial_layer_acceleration": {
        "min": 500,
        "max": 500,
        "samples": 291
      },
      "initial_layer_infill_speed": {
        "min": 28,
        "max": 105,
        "samples": 495
      },
      "initial_layer_line_width": {
        "min": 0.25,
        "max": 0.82,
        "samples": 31
      },
      "initial_layer_print_height": {
        "min": 0.1,
        "max": 0.4,
        "samples": 31
      },
      "initial_layer_speed": {
        "min": 16,
        "max": 100,
        "samples": 592
      },
      "initial_layer_travel_acceleration": {
        "min": 5000,
        "max": 6000,
        "samples": 291
      },
      "inner_wall_acceleration": {
        "min": 0,
        "max": 0,
        "samples": 291
      },
      "inner_wall_line_width": {
        "min": 0.22,
        "max": 0.82,
        "samples": 31
      },
      "inner_wall_speed": {
        "min": 40,
        "max": 600,
        "samples": 444
      },
      "interface_shells": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "internal_bridge_support_thickness": {
        "min": 0.8,
        "max": 0.8,
        "samples": 1
      },
      "internal_solid_infill_line_width": {
        "min": 0.22,
        "max": 0.82,
        "samples": 31
      },
      "internal_solid_infill_speed": {
        "min": 40,
        "max": 600,
        "samples": 460
      },
      "ironing_flow": {
        "min": 8,
        "max": 25,
        "samples": 9
      },
      "ironing_inset": {
        "min": 0.11,
        "max": 0.41,
        "samples": 31
      },
      "ironing_spacing": {
        "min": 0.15,
        "max": 0.15,
        "samples": 1
      },
      "ironing_speed": {
        "min": 20,
        "max": 30,
        "samples": 5
      },
      "layer_height": {
        "min": 0.06,
        "max": 0.56,
        "samples": 41
      },
      "layer_time_smoothing": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "layer_time_smoothing_threshold": {
        "min": 30,
        "max": 30,
        "samples": 1
      },
      "line_width": {
        "min": 0.22,
        "max": 0.82,
        "samples": 31
      },
      "max_bridge_length": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "max_travel_detour_distance": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "minimum_sparse_infill_area": {
        "min": 15,
        "max": 15,
        "samples": 1
      },
      "monotonic_travel_into_wall": {
        "min": 0,
        "max": 45,
        "samples": 34
      },
      "only_one_wall_top": {
        "min": 1,
        "max": 1,
        "samples": 1
      },
      "outer_wall_acceleration": {
        "min": 1000,
        "max": 6000,
        "samples": 363
      },
      "outer_wall_line_width": {
        "min": 0.22,
        "max": 0.82,
        "samples": 31
      },
      "outer_wall_speed": {
        "min": 50,
        "max": 500,
        "samples": 468
      },
      "overhang_1_4_speed": {
        "min": 0,
        "max": 60,
        "samples": 351
      },
      "overhang_2_4_speed": {
        "min": 30,
        "max": 60,
        "samples": 348
      },
      "overhang_3_4_speed": {
        "min": 10,
        "max": 60,
        "samples": 446
      },
      "overhang_4_4_speed": {
        "min": 5,
        "max": 35,
        "samples": 389
      },
      "overhang_totally_speed": {
        "min": 10,
        "max": 30,
        "samples": 292
      },
      "override_filament_scarf_seam_setting": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "pre_start_fan_time": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "prime_tower_brim_width": {
        "min": -1,
        "max": 3,
        "samples": 106
      },
      "prime_tower_enable_framework": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "prime_tower_flat_ironing": {
        "min": 0,
        "max": 1,
        "samples": 34
      },
      "prime_tower_lift_height": {
        "min": -1,
        "max": -1,
        "samples": 1
      },
      "prime_tower_lift_speed": {
        "min": 90,
        "max": 90,
        "samples": 1
      },
      "prime_tower_max_speed": {
        "min": 90,
        "max": 90,
        "samples": 1
      },
      "prime_tower_width": {
        "min": 35,
        "max": 60,
        "samples": 89
      },
      "print_extruder_id": {
        "min": 1,
        "max": 2,
        "samples": 291
      },
      "raft_layers": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "reduce_crossing_wall": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "resolution": {
        "min": 0.012,
        "max": 0.012,
        "samples": 1
      },
      "scarf_angle_threshold": {
        "min": 155,
        "max": 155,
        "samples": 1
      },
      "seam_placement_away_from_overhangs": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "seam_slope_gap": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "seam_slope_min_length": {
        "min": 10,
        "max": 10,
        "samples": 1
      },
      "seam_slope_start_height": {
        "min": 10,
        "max": 10,
        "samples": 1
      },
      "skeleton_infill_density": {
        "min": 15,
        "max": 25,
        "samples": 9
      },
      "skeleton_infill_line_width": {
        "min": 0.22,
        "max": 0.82,
        "samples": 31
      },
      "skin_infill_density": {
        "min": 15,
        "max": 25,
        "samples": 9
      },
      "skin_infill_depth": {
        "min": 2,
        "max": 2,
        "samples": 1
      },
      "skin_infill_line_width": {
        "min": 0.22,
        "max": 0.82,
        "samples": 31
      },
      "skirt_distance": {
        "min": 2,
        "max": 2,
        "samples": 1
      },
      "skirt_height": {
        "min": 1,
        "max": 1,
        "samples": 1
      },
      "skirt_loops": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "skirt_per_object": {
        "min": 1,
        "max": 1,
        "samples": 1
      },
      "slowdown_end_acc": {
        "min": 1000,
        "max": 100000,
        "samples": 307
      },
      "slowdown_end_height": {
        "min": 225,
        "max": 400,
        "samples": 307
      },
      "slowdown_end_speed": {
        "min": 500,
        "max": 1000,
        "samples": 299
      },
      "slowdown_start_acc": {
        "min": 8000,
        "max": 100000,
        "samples": 299
      },
      "slowdown_start_height": {
        "min": 0,
        "max": 150,
        "samples": 298
      },
      "slowdown_start_speed": {
        "min": 500,
        "max": 1000,
        "samples": 299
      },
      "small_perimeter_speed": {
        "min": 50,
        "max": 50,
        "samples": 291
      },
      "small_perimeter_threshold": {
        "min": 0,
        "max": 0,
        "samples": 291
      },
      "smooth_coefficient": {
        "min": 1,
        "max": 150,
        "samples": 80
      },
      "solid_infill_filament": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "sparse_infill_acceleration": {
        "min": 100,
        "max": 100,
        "samples": 291
      },
      "sparse_infill_density": {
        "min": 15,
        "max": 25,
        "samples": 9
      },
      "sparse_infill_filament": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "sparse_infill_lattice_angle_1": {
        "min": -45,
        "max": -45,
        "samples": 1
      },
      "sparse_infill_lattice_angle_2": {
        "min": 45,
        "max": 45,
        "samples": 1
      },
      "sparse_infill_line_width": {
        "min": 0.22,
        "max": 0.82,
        "samples": 31
      },
      "sparse_infill_speed": {
        "min": 50,
        "max": 600,
        "samples": 535
      },
      "spiral_mode": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "standby_temperature_delta": {
        "min": -5,
        "max": -5,
        "samples": 1
      },
      "support_base_pattern_spacing": {
        "min": 2.5,
        "max": 2.5,
        "samples": 1
      },
      "support_bottom_z_distance": {
        "min": 0.06,
        "max": 0.2,
        "samples": 19
      },
      "support_expansion": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "support_filament": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "support_interface_bottom_layers": {
        "min": 2,
        "max": 2,
        "samples": 1
      },
      "support_interface_filament": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "support_interface_loop_pattern": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "support_interface_spacing": {
        "min": 0.5,
        "max": 0.5,
        "samples": 1
      },
      "support_interface_speed": {
        "min": 80,
        "max": 80,
        "samples": 291
      },
      "support_interface_top_layers": {
        "min": 2,
        "max": 2,
        "samples": 1
      },
      "support_ironing_direction": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "support_ironing_flow": {
        "min": 10,
        "max": 10,
        "samples": 1
      },
      "support_ironing_inset": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "support_ironing_spacing": {
        "min": 0.15,
        "max": 0.15,
        "samples": 1
      },
      "support_ironing_speed": {
        "min": 30,
        "max": 30,
        "samples": 1
      },
      "support_line_width": {
        "min": 0.22,
        "max": 0.82,
        "samples": 32
      },
      "support_object_xy_distance": {
        "min": 0.35,
        "max": 0.35,
        "samples": 1
      },
      "support_on_build_plate_only": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "support_speed": {
        "min": 40,
        "max": 150,
        "samples": 292
      },
      "support_threshold_angle": {
        "min": 15,
        "max": 40,
        "samples": 11
      },
      "support_top_z_distance": {
        "min": 0.06,
        "max": 0.2,
        "samples": 19
      },
      "symmetric_infill_y_axis": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "top_color_penetration_layers": {
        "min": 3,
        "max": 9,
        "samples": 29
      },
      "top_shell_layers": {
        "min": 3,
        "max": 9,
        "samples": 33
      },
      "top_shell_thickness": {
        "min": 0.6,
        "max": 1,
        "samples": 17
      },
      "top_solid_infill_flow_ratio": {
        "min": 1,
        "max": 1.09,
        "samples": 291
      },
      "top_surface_acceleration": {
        "min": 1000,
        "max": 2000,
        "samples": 295
      },
      "top_surface_density": {
        "min": 100,
        "max": 100,
        "samples": 1
      },
      "top_surface_line_width": {
        "min": 0.22,
        "max": 0.82,
        "samples": 35
      },
      "top_surface_speed": {
        "min": 30,
        "max": 300,
        "samples": 476
      },
      "travel_acceleration": {
        "min": 4000,
        "max": 10000,
        "samples": 307
      },
      "travel_short_distance_acceleration": {
        "min": 250,
        "max": 250,
        "samples": 291
      },
      "travel_speed": {
        "min": 300,
        "max": 1000,
        "samples": 510
      },
      "travel_speed_z": {
        "min": 0,
        "max": 0,
        "samples": 291
      },
      "tree_support_branch_angle": {
        "min": 45,
        "max": 45,
        "samples": 1
      },
      "tree_support_branch_diameter": {
        "min": 2,
        "max": 2,
        "samples": 1
      },
      "tree_support_wall_count": {
        "min": -1,
        "max": -1,
        "samples": 1
      },
      "vertical_shell_speed": {
        "min": 80,
        "max": 80,
        "samples": 291
      },
      "wall_filament": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "wall_loops": {
        "min": 2,
        "max": 6,
        "samples": 19
      },
      "wipe_tower_no_sparse_layers": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "xy_contour_compensation": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "xy_hole_compensation": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "z_direction_outwall_speed_continuous": {
        "min": 0,
        "max": 1,
        "samples": 2
      }
    },
    "booleanKeys": [
      "adaptive_layer_height",
      "avoid_crossing_wall_includes_support",
      "bottom_shell_thickness",
      "bridge_no_support",
      "circle_compensation_manual_offset",
      "detect_floating_vertical_shell",
      "detect_overhang_wall",
      "detect_thin_wall",
      "enable_arc_fitting",
      "enable_circle_compensation",
      "enable_height_slowdown",
      "enable_overhang_speed",
      "enable_prime_tower",
      "enable_support",
      "enable_support_ironing",
      "enable_tower_interface_features",
      "enable_wrapping_detection",
      "fill_multiline",
      "fuzzy_skin_first_layer",
      "infill_combination",
      "infill_instead_top_bottom_surfaces",
      "infill_rotate_step",
      "inner_wall_acceleration",
      "instantiation",
      "interface_shells",
      "layer_time_smoothing",
      "max_bridge_length",
      "max_travel_detour_distance",
      "only_one_wall_top",
      "override_filament_scarf_seam_setting",
      "pre_start_fan_time",
      "prime_tower_enable_framework",
      "prime_tower_flat_ironing",
      "raft_layers",
      "reduce_crossing_wall",
      "seam_placement_away_from_overhangs",
      "seam_slope_gap",
      "skirt_height",
      "skirt_loops",
      "skirt_per_object",
      "small_perimeter_threshold",
      "solid_infill_filament",
      "sparse_infill_filament",
      "spiral_mode",
      "support_expansion",
      "support_filament",
      "support_interface_filament",
      "support_interface_loop_pattern",
      "support_ironing_direction",
      "support_on_build_plate_only",
      "symmetric_infill_y_axis",
      "travel_speed_z",
      "wall_filament",
      "wipe_tower_no_sparse_layers",
      "xy_contour_compensation",
      "xy_hole_compensation",
      "z_direction_outwall_speed_continuous"
    ],
    "categoricalValues": {
      "bottom_surface_pattern": [
        "monotonic"
      ],
      "draft_shield": [
        "disabled"
      ],
      "fuzzy_skin": [
        "none"
      ],
      "fuzzy_skin_mode": [
        "displacement"
      ],
      "fuzzy_skin_noise_type": [
        "classic"
      ],
      "instantiation": [
        "false",
        "true"
      ],
      "ironing_type": [
        "no ironing"
      ],
      "locked_skeleton_infill_pattern": [
        "zigzag"
      ],
      "locked_skin_infill_pattern": [
        "crosszag"
      ],
      "print_extruder_variant": [
        "Bowden High Flow",
        "Bowden Standard",
        "Direct Drive High Flow",
        "Direct Drive Standard",
        "Direct Drive TPU High Flow",
        "Direct Drive TPU285"
      ],
      "print_sequence": [
        "by layer"
      ],
      "reduce_infill_retraction_mode": [
        "Auto"
      ],
      "seam_position": [
        "aligned"
      ],
      "seam_slope_type": [
        "none"
      ],
      "sparse_infill_pattern": [
        "grid",
        "gyroid"
      ],
      "support_base_pattern": [
        "default"
      ],
      "support_interface_pattern": [
        "auto"
      ],
      "support_ironing_pattern": [
        "zig-zag"
      ],
      "support_style": [
        "default"
      ],
      "support_type": [
        "tree(auto)"
      ],
      "top_surface_pattern": [
        "monotonic",
        "monotonicline"
      ],
      "type": [
        "process"
      ],
      "wall_generator": [
        "classic"
      ],
      "wall_infill_order": [
        "inner wall/outer wall/infill"
      ]
    },
    "valueShapes": {
      "adaptive_layer_height": "scalar",
      "avoid_crossing_wall_includes_support": "scalar",
      "bottom_color_penetration_layers": "scalar",
      "bottom_shell_layers": "scalar",
      "bottom_shell_thickness": "scalar",
      "bottom_surface_density": "scalar",
      "bottom_surface_pattern": "scalar",
      "bridge_flow": "scalar",
      "bridge_no_support": "scalar",
      "bridge_speed": "array",
      "brim_object_gap": "scalar",
      "brim_width": "scalar",
      "circle_compensation_manual_offset": "scalar",
      "compatible_printers": "array",
      "compatible_printers_condition": "scalar",
      "default_acceleration": "array",
      "description": "scalar",
      "detect_floating_vertical_shell": "scalar",
      "detect_overhang_wall": "scalar",
      "detect_thin_wall": "scalar",
      "draft_shield": "scalar",
      "elefant_foot_compensation": "scalar",
      "enable_arc_fitting": "scalar",
      "enable_circle_compensation": "scalar",
      "enable_height_slowdown": "array",
      "enable_overhang_speed": "array",
      "enable_prime_tower": "scalar",
      "enable_support": "scalar",
      "enable_support_ironing": "scalar",
      "enable_tower_interface_features": "scalar",
      "enable_wrapping_detection": "scalar",
      "filename_format": "scalar",
      "fill_multiline": "scalar",
      "from": "scalar",
      "fuzzy_skin": "scalar",
      "fuzzy_skin_first_layer": "scalar",
      "fuzzy_skin_mode": "scalar",
      "fuzzy_skin_noise_type": "scalar",
      "fuzzy_skin_octaves": "scalar",
      "fuzzy_skin_persistence": "scalar",
      "fuzzy_skin_point_distance": "scalar",
      "fuzzy_skin_scale": "scalar",
      "fuzzy_skin_thickness": "scalar",
      "gap_infill_speed": "array",
      "infill_combination": "scalar",
      "infill_direction": "scalar",
      "infill_instead_top_bottom_surfaces": "scalar",
      "infill_lock_depth": "scalar",
      "infill_rotate_step": "scalar",
      "infill_shift_step": "scalar",
      "infill_wall_overlap": "scalar",
      "inherits": "scalar",
      "initial_layer_acceleration": "array",
      "initial_layer_infill_speed": "array",
      "initial_layer_line_width": "scalar",
      "initial_layer_print_height": "scalar",
      "initial_layer_speed": "array",
      "initial_layer_travel_acceleration": "array",
      "inner_wall_acceleration": "array",
      "inner_wall_line_width": "scalar",
      "inner_wall_speed": "array",
      "instantiation": "scalar",
      "interface_shells": "scalar",
      "internal_bridge_support_thickness": "scalar",
      "internal_solid_infill_line_width": "scalar",
      "internal_solid_infill_speed": "array",
      "ironing_flow": "scalar",
      "ironing_inset": "scalar",
      "ironing_spacing": "scalar",
      "ironing_speed": "scalar",
      "ironing_type": "scalar",
      "layer_height": "scalar",
      "layer_time_smoothing": "scalar",
      "layer_time_smoothing_threshold": "scalar",
      "line_width": "scalar",
      "locked_skeleton_infill_pattern": "scalar",
      "locked_skin_infill_pattern": "scalar",
      "max_bridge_length": "scalar",
      "max_travel_detour_distance": "scalar",
      "minimum_sparse_infill_area": "scalar",
      "monotonic_travel_into_wall": "scalar",
      "name": "scalar",
      "only_one_wall_top": "scalar",
      "outer_wall_acceleration": "array",
      "outer_wall_line_width": "scalar",
      "outer_wall_speed": "array",
      "overhang_1_4_speed": "array",
      "overhang_2_4_speed": "array",
      "overhang_3_4_speed": "array",
      "overhang_4_4_speed": "array",
      "overhang_totally_speed": "array",
      "override_filament_scarf_seam_setting": "scalar",
      "pre_start_fan_time": "array",
      "prime_tower_brim_width": "scalar",
      "prime_tower_enable_framework": "scalar",
      "prime_tower_flat_ironing": "scalar",
      "prime_tower_lift_height": "scalar",
      "prime_tower_lift_speed": "scalar",
      "prime_tower_max_speed": "scalar",
      "prime_tower_width": "scalar",
      "print_extruder_id": "array",
      "print_extruder_variant": "array",
      "print_sequence": "scalar",
      "print_settings_id": "scalar",
      "raft_layers": "scalar",
      "reduce_crossing_wall": "scalar",
      "reduce_infill_retraction_mode": "scalar",
      "resolution": "scalar",
      "scarf_angle_threshold": "scalar",
      "seam_placement_away_from_overhangs": "scalar",
      "seam_position": "scalar",
      "seam_slope_gap": "scalar",
      "seam_slope_min_length": "scalar",
      "seam_slope_start_height": "scalar",
      "seam_slope_type": "scalar",
      "setting_id": "scalar",
      "skeleton_infill_density": "scalar",
      "skeleton_infill_line_width": "scalar",
      "skin_infill_density": "scalar",
      "skin_infill_depth": "scalar",
      "skin_infill_line_width": "scalar",
      "skirt_distance": "scalar",
      "skirt_height": "scalar",
      "skirt_loops": "scalar",
      "skirt_per_object": "scalar",
      "slowdown_end_acc": "array",
      "slowdown_end_height": "array",
      "slowdown_end_speed": "array",
      "slowdown_start_acc": "array",
      "slowdown_start_height": "array",
      "slowdown_start_speed": "array",
      "small_perimeter_speed": "array",
      "small_perimeter_threshold": "array",
      "smooth_coefficient": "scalar",
      "solid_infill_filament": "scalar",
      "sparse_infill_acceleration": "array",
      "sparse_infill_density": "scalar",
      "sparse_infill_filament": "scalar",
      "sparse_infill_lattice_angle_1": "scalar",
      "sparse_infill_lattice_angle_2": "scalar",
      "sparse_infill_line_width": "scalar",
      "sparse_infill_pattern": "scalar",
      "sparse_infill_speed": "array",
      "spiral_mode": "scalar",
      "standby_temperature_delta": "scalar",
      "support_base_pattern": "scalar",
      "support_base_pattern_spacing": "scalar",
      "support_bottom_z_distance": "scalar",
      "support_expansion": "scalar",
      "support_filament": "scalar",
      "support_interface_bottom_layers": "scalar",
      "support_interface_filament": "scalar",
      "support_interface_loop_pattern": "scalar",
      "support_interface_pattern": "scalar",
      "support_interface_spacing": "scalar",
      "support_interface_speed": "array",
      "support_interface_top_layers": "scalar",
      "support_ironing_direction": "scalar",
      "support_ironing_flow": "scalar",
      "support_ironing_inset": "scalar",
      "support_ironing_pattern": "scalar",
      "support_ironing_spacing": "scalar",
      "support_ironing_speed": "scalar",
      "support_line_width": "scalar",
      "support_object_xy_distance": "scalar",
      "support_on_build_plate_only": "scalar",
      "support_speed": "array",
      "support_style": "scalar",
      "support_threshold_angle": "scalar",
      "support_top_z_distance": "scalar",
      "support_type": "scalar",
      "symmetric_infill_y_axis": "scalar",
      "top_color_penetration_layers": "scalar",
      "top_shell_layers": "scalar",
      "top_shell_thickness": "scalar",
      "top_solid_infill_flow_ratio": "array",
      "top_surface_acceleration": "array",
      "top_surface_density": "scalar",
      "top_surface_line_width": "scalar",
      "top_surface_pattern": "scalar",
      "top_surface_speed": "array",
      "travel_acceleration": "array",
      "travel_short_distance_acceleration": "array",
      "travel_speed": "array",
      "travel_speed_z": "array",
      "tree_support_branch_angle": "scalar",
      "tree_support_branch_diameter": "scalar",
      "tree_support_wall_count": "scalar",
      "type": "scalar",
      "vertical_shell_speed": "array",
      "wall_filament": "scalar",
      "wall_generator": "scalar",
      "wall_infill_order": "scalar",
      "wall_loops": "scalar",
      "wipe_tower_no_sparse_layers": "scalar",
      "xy_contour_compensation": "scalar",
      "xy_hole_compensation": "scalar",
      "z_direction_outwall_speed_continuous": "scalar"
    }
  },
  "filament": {
    "fileCount": 1873,
    "knownKeys": [
      "activate_air_filtration",
      "additional_cooling_fan_speed",
      "additional_fan_full_speed_layer",
      "chamber_temperatures",
      "circle_compensation_speed",
      "close_additional_fan_first_x_layers",
      "close_fan_the_first_x_layers",
      "compatible_printers",
      "complete_print_exhaust_fan_speed",
      "cool_plate_temp",
      "cool_plate_temp_initial_layer",
      "cooling_perimeter_transition_distance",
      "cooling_slowdown_logic",
      "counter_coef_1",
      "counter_coef_2",
      "counter_coef_3",
      "counter_limit_max",
      "counter_limit_min",
      "description",
      "diameter_limit",
      "during_print_exhaust_fan_speed",
      "eng_plate_temp",
      "eng_plate_temp_initial_layer",
      "fan_cooling_layer_time",
      "fan_max_speed",
      "fan_min_speed",
      "filament_adaptive_volumetric_speed",
      "filament_adhesiveness_category",
      "filament_bridge_speed",
      "filament_change_length",
      "filament_change_length_nc",
      "filament_contact_safe",
      "filament_cooling_before_tower",
      "filament_cost",
      "filament_density",
      "filament_deretraction_speed",
      "filament_dev_ams_drying_ams_limitations",
      "filament_dev_ams_drying_heat_distortion_temperature",
      "filament_dev_ams_drying_temperature",
      "filament_dev_ams_drying_time",
      "filament_dev_chamber_drying_bed_temperature",
      "filament_dev_chamber_drying_time",
      "filament_dev_drying_cooling_temperature",
      "filament_dev_drying_softening_temperature",
      "filament_diameter",
      "filament_emission_safe",
      "filament_enable_overhang_speed",
      "filament_end_gcode",
      "filament_extruder_compatibility",
      "filament_extruder_id",
      "filament_extruder_variant",
      "filament_flow_ratio",
      "filament_flush_temp",
      "filament_flush_temp_fast",
      "filament_flush_volumetric_speed",
      "filament_id",
      "filament_ingredients_safe",
      "filament_is_support",
      "filament_long_retractions_when_cut",
      "filament_long_retractions_when_ec",
      "filament_max_volumetric_speed",
      "filament_metal_stickiness",
      "filament_minimal_purge_on_wipe_tower",
      "filament_overhang_1_4_speed",
      "filament_overhang_2_4_speed",
      "filament_overhang_3_4_speed",
      "filament_overhang_4_4_speed",
      "filament_overhang_totally_speed",
      "filament_pre_cooling_temperature",
      "filament_pre_cooling_temperature_nc",
      "filament_preheat_temperature_delta",
      "filament_prime_volume",
      "filament_prime_volume_nc",
      "filament_printable",
      "filament_ramming_travel_time",
      "filament_ramming_travel_time_nc",
      "filament_ramming_volumetric_speed",
      "filament_ramming_volumetric_speed_nc",
      "filament_retract_before_wipe",
      "filament_retract_length_nc",
      "filament_retract_restart_extra",
      "filament_retract_when_changing_layer",
      "filament_retraction_distances_when_cut",
      "filament_retraction_distances_when_ec",
      "filament_retraction_length",
      "filament_retraction_minimum_travel",
      "filament_retraction_speed",
      "filament_scarf_gap",
      "filament_scarf_height",
      "filament_scarf_length",
      "filament_scarf_seam_type",
      "filament_settings_id",
      "filament_shrink",
      "filament_soluble",
      "filament_start_gcode",
      "filament_support_printable",
      "filament_tower_interface_pre_extrusion_dist",
      "filament_tower_interface_pre_extrusion_length",
      "filament_tower_interface_print_temp",
      "filament_tower_interface_purge_volume",
      "filament_tower_ironing_area",
      "filament_type",
      "filament_velocity_adaptation_factor",
      "filament_vendor",
      "filament_wipe",
      "filament_wipe_distance",
      "filament_z_hop",
      "filament_z_hop_types",
      "first_x_layer_fan_speed",
      "from",
      "full_fan_speed_layer",
      "hole_coef_1",
      "hole_coef_2",
      "hole_coef_3",
      "hole_limit_max",
      "hole_limit_min",
      "hot_plate_temp",
      "hot_plate_temp_initial_layer",
      "impact_strength_z",
      "include",
      "inherits",
      "instantiation",
      "long_retractions_when_ec",
      "name",
      "no_slow_down_for_cooling_on_outwalls",
      "nozzle_temperature",
      "nozzle_temperature_initial_layer",
      "nozzle_temperature_range_high",
      "nozzle_temperature_range_low",
      "overhang_fan_speed",
      "overhang_fan_threshold",
      "override_process_overhang_speed",
      "pre_start_fan_time",
      "reduce_fan_stop_start_freq",
      "required_nozzle_HRC",
      "retraction_distances_when_ec",
      "setting_id",
      "slow_down_for_layer_cooling",
      "slow_down_layer_time",
      "slow_down_min_speed",
      "supertack_plate_temp",
      "supertack_plate_temp_initial_layer",
      "temperature_vitrification",
      "textured_plate_temp",
      "textured_plate_temp_initial_layer",
      "type",
      "volumetric_speed_coefficients"
    ],
    "numericBounds": {
      "activate_air_filtration": {
        "min": 0,
        "max": 1,
        "samples": 22
      },
      "additional_cooling_fan_speed": {
        "min": 0,
        "max": 100,
        "samples": 258
      },
      "additional_fan_full_speed_layer": {
        "min": 0,
        "max": 2,
        "samples": 15
      },
      "chamber_temperatures": {
        "min": 0,
        "max": 65,
        "samples": 293
      },
      "circle_compensation_speed": {
        "min": 200,
        "max": 200,
        "samples": 1
      },
      "close_additional_fan_first_x_layers": {
        "min": 1,
        "max": 3,
        "samples": 9
      },
      "close_fan_the_first_x_layers": {
        "min": 1,
        "max": 3,
        "samples": 9
      },
      "complete_print_exhaust_fan_speed": {
        "min": 70,
        "max": 70,
        "samples": 1
      },
      "cool_plate_temp": {
        "min": 0,
        "max": 60,
        "samples": 34
      },
      "cool_plate_temp_initial_layer": {
        "min": 0,
        "max": 60,
        "samples": 34
      },
      "cooling_perimeter_transition_distance": {
        "min": 10,
        "max": 10,
        "samples": 1
      },
      "counter_coef_1": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "counter_coef_2": {
        "min": -0.0036,
        "max": 0.06,
        "samples": 186
      },
      "counter_coef_3": {
        "min": -0.32,
        "max": 0.0241,
        "samples": 186
      },
      "counter_limit_max": {
        "min": -0.0975,
        "max": 0.3341,
        "samples": 184
      },
      "counter_limit_min": {
        "min": -0.4,
        "max": 0.0241,
        "samples": 155
      },
      "diameter_limit": {
        "min": 50,
        "max": 50,
        "samples": 1
      },
      "during_print_exhaust_fan_speed": {
        "min": 70,
        "max": 70,
        "samples": 1
      },
      "eng_plate_temp": {
        "min": 0,
        "max": 110,
        "samples": 733
      },
      "eng_plate_temp_initial_layer": {
        "min": 0,
        "max": 110,
        "samples": 730
      },
      "fan_cooling_layer_time": {
        "min": 4,
        "max": 242,
        "samples": 418
      },
      "fan_max_speed": {
        "min": 20,
        "max": 100,
        "samples": 531
      },
      "fan_min_speed": {
        "min": 0,
        "max": 100,
        "samples": 544
      },
      "filament_adaptive_volumetric_speed": {
        "min": 0,
        "max": 0,
        "samples": 43
      },
      "filament_adhesiveness_category": {
        "min": 100,
        "max": 902,
        "samples": 22
      },
      "filament_bridge_speed": {
        "min": 25,
        "max": 50,
        "samples": 51
      },
      "filament_change_length": {
        "min": 4,
        "max": 12,
        "samples": 329
      },
      "filament_change_length_nc": {
        "min": 4,
        "max": 10,
        "samples": 190
      },
      "filament_contact_safe": {
        "min": 1,
        "max": 1,
        "samples": 1
      },
      "filament_cooling_before_tower": {
        "min": 0,
        "max": 10,
        "samples": 2337
      },
      "filament_cost": {
        "min": 0,
        "max": 240,
        "samples": 114
      },
      "filament_density": {
        "min": 0,
        "max": 1.4,
        "samples": 118
      },
      "filament_deretraction_speed": {
        "min": 0,
        "max": 50,
        "samples": 162
      },
      "filament_dev_ams_drying_ams_limitations": {
        "min": -1,
        "max": 1,
        "samples": 24
      },
      "filament_dev_ams_drying_heat_distortion_temperature": {
        "min": 45,
        "max": 165,
        "samples": 25
      },
      "filament_dev_ams_drying_temperature": {
        "min": 40,
        "max": 85,
        "samples": 108
      },
      "filament_dev_ams_drying_time": {
        "min": 4,
        "max": 18,
        "samples": 80
      },
      "filament_dev_chamber_drying_bed_temperature": {
        "min": 70,
        "max": 100,
        "samples": 16
      },
      "filament_dev_chamber_drying_time": {
        "min": 12,
        "max": 18,
        "samples": 8
      },
      "filament_dev_drying_cooling_temperature": {
        "min": 35,
        "max": 150,
        "samples": 27
      },
      "filament_dev_drying_softening_temperature": {
        "min": 40,
        "max": 150,
        "samples": 27
      },
      "filament_diameter": {
        "min": 1.75,
        "max": 1.75,
        "samples": 1
      },
      "filament_emission_safe": {
        "min": 1,
        "max": 1,
        "samples": 1
      },
      "filament_enable_overhang_speed": {
        "min": 1,
        "max": 1,
        "samples": 43
      },
      "filament_extruder_compatibility": {
        "min": 0,
        "max": 24,
        "samples": 58
      },
      "filament_extruder_id": {
        "min": 1,
        "max": 1,
        "samples": 10
      },
      "filament_flow_ratio": {
        "min": 0.52,
        "max": 1.1,
        "samples": 2635
      },
      "filament_flush_temp": {
        "min": 0,
        "max": 240,
        "samples": 121
      },
      "filament_flush_temp_fast": {
        "min": 0,
        "max": 255,
        "samples": 102
      },
      "filament_flush_volumetric_speed": {
        "min": 0,
        "max": 3,
        "samples": 303
      },
      "filament_ingredients_safe": {
        "min": 1,
        "max": 1,
        "samples": 1
      },
      "filament_is_support": {
        "min": 0,
        "max": 1,
        "samples": 10
      },
      "filament_long_retractions_when_cut": {
        "min": 0,
        "max": 1,
        "samples": 423
      },
      "filament_max_volumetric_speed": {
        "min": 0,
        "max": 40,
        "samples": 3384
      },
      "filament_minimal_purge_on_wipe_tower": {
        "min": 15,
        "max": 15,
        "samples": 1
      },
      "filament_overhang_1_4_speed": {
        "min": 0,
        "max": 0,
        "samples": 43
      },
      "filament_overhang_2_4_speed": {
        "min": 25,
        "max": 50,
        "samples": 45
      },
      "filament_overhang_3_4_speed": {
        "min": 25,
        "max": 30,
        "samples": 45
      },
      "filament_overhang_4_4_speed": {
        "min": 10,
        "max": 35,
        "samples": 58
      },
      "filament_overhang_totally_speed": {
        "min": 10,
        "max": 30,
        "samples": 59
      },
      "filament_pre_cooling_temperature": {
        "min": 0,
        "max": 210,
        "samples": 85
      },
      "filament_pre_cooling_temperature_nc": {
        "min": 0,
        "max": 280,
        "samples": 421
      },
      "filament_preheat_temperature_delta": {
        "min": 0,
        "max": 20,
        "samples": 417
      },
      "filament_prime_volume": {
        "min": 30,
        "max": 60,
        "samples": 294
      },
      "filament_prime_volume_nc": {
        "min": 30,
        "max": 60,
        "samples": 190
      },
      "filament_printable": {
        "min": 0,
        "max": 3,
        "samples": 45
      },
      "filament_ramming_travel_time": {
        "min": 0,
        "max": 20,
        "samples": 3059
      },
      "filament_ramming_travel_time_nc": {
        "min": 0,
        "max": 20,
        "samples": 419
      },
      "filament_ramming_volumetric_speed": {
        "min": -1,
        "max": 4.5,
        "samples": 103
      },
      "filament_ramming_volumetric_speed_nc": {
        "min": -1,
        "max": 4.5,
        "samples": 69
      },
      "filament_retract_before_wipe": {
        "min": 0,
        "max": 0,
        "samples": 76
      },
      "filament_retract_length_nc": {
        "min": 10,
        "max": 18,
        "samples": 225
      },
      "filament_retraction_distances_when_cut": {
        "min": 0,
        "max": 18,
        "samples": 686
      },
      "filament_retraction_length": {
        "min": 0.2,
        "max": 5,
        "samples": 1085
      },
      "filament_retraction_speed": {
        "min": 0.4,
        "max": 200,
        "samples": 176
      },
      "filament_scarf_gap": {
        "min": 0,
        "max": 15,
        "samples": 12
      },
      "filament_scarf_height": {
        "min": 5,
        "max": 10,
        "samples": 11
      },
      "filament_scarf_length": {
        "min": 10,
        "max": 10,
        "samples": 7
      },
      "filament_shrink": {
        "min": 100,
        "max": 100,
        "samples": 1
      },
      "filament_soluble": {
        "min": 0,
        "max": 1,
        "samples": 2
      },
      "filament_support_printable": {
        "min": 2,
        "max": 2,
        "samples": 2
      },
      "filament_tower_interface_pre_extrusion_dist": {
        "min": 10,
        "max": 10,
        "samples": 1
      },
      "filament_tower_interface_pre_extrusion_length": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "filament_tower_interface_print_temp": {
        "min": -1,
        "max": 290,
        "samples": 186
      },
      "filament_tower_interface_purge_volume": {
        "min": 20,
        "max": 20,
        "samples": 1
      },
      "filament_tower_ironing_area": {
        "min": 4,
        "max": 8,
        "samples": 40
      },
      "filament_velocity_adaptation_factor": {
        "min": 1,
        "max": 1,
        "samples": 1
      },
      "filament_wipe": {
        "min": 1,
        "max": 1,
        "samples": 738
      },
      "filament_wipe_distance": {
        "min": 0,
        "max": 5,
        "samples": 755
      },
      "filament_z_hop": {
        "min": 0,
        "max": 1,
        "samples": 131
      },
      "first_x_layer_fan_speed": {
        "min": 0,
        "max": 40,
        "samples": 425
      },
      "full_fan_speed_layer": {
        "min": 0,
        "max": 2,
        "samples": 15
      },
      "hole_coef_1": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "hole_coef_2": {
        "min": -0.0121,
        "max": 0.0013,
        "samples": 169
      },
      "hole_coef_3": {
        "min": 0.0725,
        "max": 0.35043,
        "samples": 175
      },
      "hole_limit_max": {
        "min": 0.095,
        "max": 0.22,
        "samples": 146
      },
      "hole_limit_min": {
        "min": -0.088,
        "max": 0.1686,
        "samples": 156
      },
      "hot_plate_temp": {
        "min": 30,
        "max": 110,
        "samples": 333
      },
      "hot_plate_temp_initial_layer": {
        "min": 30,
        "max": 110,
        "samples": 333
      },
      "impact_strength_z": {
        "min": 2.8,
        "max": 88.7,
        "samples": 62
      },
      "long_retractions_when_ec": {
        "min": 0,
        "max": 1,
        "samples": 1387
      },
      "no_slow_down_for_cooling_on_outwalls": {
        "min": 0,
        "max": 0,
        "samples": 1
      },
      "nozzle_temperature": {
        "min": 200,
        "max": 320,
        "samples": 3164
      },
      "nozzle_temperature_initial_layer": {
        "min": 200,
        "max": 320,
        "samples": 3152
      },
      "nozzle_temperature_range_high": {
        "min": 220,
        "max": 340,
        "samples": 84
      },
      "nozzle_temperature_range_low": {
        "min": 175,
        "max": 310,
        "samples": 83
      },
      "overhang_fan_speed": {
        "min": 30,
        "max": 100,
        "samples": 128
      },
      "overhang_fan_threshold": {
        "min": 0,
        "max": 95,
        "samples": 137
      },
      "override_process_overhang_speed": {
        "min": 0,
        "max": 1,
        "samples": 50
      },
      "pre_start_fan_time": {
        "min": 0,
        "max": 2,
        "samples": 419
      },
      "reduce_fan_stop_start_freq": {
        "min": 0,
        "max": 1,
        "samples": 54
      },
      "required_nozzle_HRC": {
        "min": 3,
        "max": 40,
        "samples": 16
      },
      "retraction_distances_when_ec": {
        "min": 0,
        "max": 10,
        "samples": 2171
      },
      "slow_down_for_layer_cooling": {
        "min": 0,
        "max": 1,
        "samples": 5
      },
      "slow_down_layer_time": {
        "min": 0,
        "max": 25,
        "samples": 580
      },
      "slow_down_min_speed": {
        "min": 10,
        "max": 50,
        "samples": 2677
      },
      "supertack_plate_temp": {
        "min": 0,
        "max": 80,
        "samples": 409
      },
      "supertack_plate_temp_initial_layer": {
        "min": 0,
        "max": 80,
        "samples": 396
      },
      "temperature_vitrification": {
        "min": 30,
        "max": 220,
        "samples": 158
      },
      "textured_plate_temp": {
        "min": 30,
        "max": 110,
        "samples": 336
      },
      "textured_plate_temp_initial_layer": {
        "min": 30,
        "max": 110,
        "samples": 347
      }
    },
    "booleanKeys": [
      "activate_air_filtration",
      "counter_coef_1",
      "filament_adaptive_volumetric_speed",
      "filament_contact_safe",
      "filament_emission_safe",
      "filament_enable_overhang_speed",
      "filament_extruder_id",
      "filament_ingredients_safe",
      "filament_is_support",
      "filament_overhang_1_4_speed",
      "filament_soluble",
      "filament_tower_interface_pre_extrusion_length",
      "filament_velocity_adaptation_factor",
      "hole_coef_1",
      "instantiation",
      "long_retractions_when_ec",
      "no_slow_down_for_cooling_on_outwalls",
      "override_process_overhang_speed",
      "reduce_fan_stop_start_freq",
      "slow_down_for_layer_cooling"
    ],
    "categoricalValues": {
      "cooling_slowdown_logic": [
        "uniform_cooling"
      ],
      "filament_deretraction_speed": [
        "nil"
      ],
      "filament_extruder_variant": [
        "Bowden High Flow",
        "Bowden Standard",
        "Direct Drive High Flow",
        "Direct Drive Standard",
        "Direct Drive TPU High Flow"
      ],
      "filament_long_retractions_when_cut": [
        "nil"
      ],
      "filament_long_retractions_when_ec": [
        "nil"
      ],
      "filament_metal_stickiness": [
        "High",
        "None"
      ],
      "filament_retract_before_wipe": [
        "nil"
      ],
      "filament_retract_restart_extra": [
        "nil"
      ],
      "filament_retract_when_changing_layer": [
        "nil"
      ],
      "filament_retraction_distances_when_cut": [
        "nil"
      ],
      "filament_retraction_distances_when_ec": [
        "nil"
      ],
      "filament_retraction_length": [
        "nil"
      ],
      "filament_retraction_minimum_travel": [
        "nil"
      ],
      "filament_retraction_speed": [
        "nil"
      ],
      "filament_scarf_seam_type": [
        "none"
      ],
      "filament_wipe": [
        "nil"
      ],
      "filament_wipe_distance": [
        "nil"
      ],
      "filament_z_hop": [
        "nil"
      ],
      "filament_z_hop_types": [
        "Auto Lift",
        "Normal Lift",
        "Slope Lift",
        "Spiral Lift",
        "nil"
      ],
      "include": [
        "fdm_filament_template_direct_bowden",
        "fdm_filament_template_direct_dual"
      ],
      "instantiation": [
        "false",
        "true"
      ],
      "textured_plate_temp_initial_layer": [
        "V"
      ],
      "type": [
        "filament"
      ],
      "volumetric_speed_coefficients": [
        "-20.9250 -1.8134 71.7462 1.9816 0.5060 -0.1901",
        "-72.1736 -8.8086 10.6201 29.6592 9.9286 -3.3920",
        "0 0 0 0 0 0",
        "12.4717 -2.8601 9.7830 2.9503 3.9235 -1.8644",
        "48.0137 -0.3915 27.3862 -32.3779 -3.9738 5.2809",
        "6.6221 -1.8351 5.4532 2.6077 3.1996 -1.9564",
        "85.1441 -0.1306 48.4938 -43.6862 -5.8088 5.5653"
      ]
    },
    "valueShapes": {
      "activate_air_filtration": "array",
      "additional_cooling_fan_speed": "array",
      "additional_fan_full_speed_layer": "array",
      "chamber_temperatures": "array",
      "circle_compensation_speed": "array",
      "close_additional_fan_first_x_layers": "array",
      "close_fan_the_first_x_layers": "array",
      "compatible_printers": "array",
      "complete_print_exhaust_fan_speed": "array",
      "cool_plate_temp": "array",
      "cool_plate_temp_initial_layer": "array",
      "cooling_perimeter_transition_distance": "array",
      "cooling_slowdown_logic": "array",
      "counter_coef_1": "array",
      "counter_coef_2": "array",
      "counter_coef_3": "array",
      "counter_limit_max": "array",
      "counter_limit_min": "array",
      "description": "scalar",
      "diameter_limit": "array",
      "during_print_exhaust_fan_speed": "array",
      "eng_plate_temp": "array",
      "eng_plate_temp_initial_layer": "array",
      "fan_cooling_layer_time": "array",
      "fan_max_speed": "array",
      "fan_min_speed": "array",
      "filament_adaptive_volumetric_speed": "array",
      "filament_adhesiveness_category": "array",
      "filament_bridge_speed": "array",
      "filament_change_length": "array",
      "filament_change_length_nc": "array",
      "filament_contact_safe": "scalar",
      "filament_cooling_before_tower": "array",
      "filament_cost": "array",
      "filament_density": "array",
      "filament_deretraction_speed": "array",
      "filament_dev_ams_drying_ams_limitations": "array",
      "filament_dev_ams_drying_heat_distortion_temperature": "array",
      "filament_dev_ams_drying_temperature": "array",
      "filament_dev_ams_drying_time": "array",
      "filament_dev_chamber_drying_bed_temperature": "array",
      "filament_dev_chamber_drying_time": "array",
      "filament_dev_drying_cooling_temperature": "array",
      "filament_dev_drying_softening_temperature": "array",
      "filament_diameter": "array",
      "filament_emission_safe": "scalar",
      "filament_enable_overhang_speed": "array",
      "filament_end_gcode": "array",
      "filament_extruder_compatibility": "array",
      "filament_extruder_id": "array",
      "filament_extruder_variant": "array",
      "filament_flow_ratio": "array",
      "filament_flush_temp": "array",
      "filament_flush_temp_fast": "array",
      "filament_flush_volumetric_speed": "array",
      "filament_id": "scalar",
      "filament_ingredients_safe": "scalar",
      "filament_is_support": "array",
      "filament_long_retractions_when_cut": "array",
      "filament_long_retractions_when_ec": "array",
      "filament_max_volumetric_speed": "array",
      "filament_metal_stickiness": "array",
      "filament_minimal_purge_on_wipe_tower": "array",
      "filament_overhang_1_4_speed": "array",
      "filament_overhang_2_4_speed": "array",
      "filament_overhang_3_4_speed": "array",
      "filament_overhang_4_4_speed": "array",
      "filament_overhang_totally_speed": "array",
      "filament_pre_cooling_temperature": "array",
      "filament_pre_cooling_temperature_nc": "array",
      "filament_preheat_temperature_delta": "array",
      "filament_prime_volume": "array",
      "filament_prime_volume_nc": "array",
      "filament_printable": "array",
      "filament_ramming_travel_time": "array",
      "filament_ramming_travel_time_nc": "array",
      "filament_ramming_volumetric_speed": "array",
      "filament_ramming_volumetric_speed_nc": "array",
      "filament_retract_before_wipe": "array",
      "filament_retract_length_nc": "array",
      "filament_retract_restart_extra": "array",
      "filament_retract_when_changing_layer": "array",
      "filament_retraction_distances_when_cut": "array",
      "filament_retraction_distances_when_ec": "array",
      "filament_retraction_length": "array",
      "filament_retraction_minimum_travel": "array",
      "filament_retraction_speed": "array",
      "filament_scarf_gap": "array",
      "filament_scarf_height": "array",
      "filament_scarf_length": "array",
      "filament_scarf_seam_type": "array",
      "filament_settings_id": "array",
      "filament_shrink": "array",
      "filament_soluble": "array",
      "filament_start_gcode": "array",
      "filament_support_printable": "array",
      "filament_tower_interface_pre_extrusion_dist": "array",
      "filament_tower_interface_pre_extrusion_length": "array",
      "filament_tower_interface_print_temp": "array",
      "filament_tower_interface_purge_volume": "array",
      "filament_tower_ironing_area": "array",
      "filament_type": "array",
      "filament_velocity_adaptation_factor": "array",
      "filament_vendor": "array",
      "filament_wipe": "array",
      "filament_wipe_distance": "array",
      "filament_z_hop": "array",
      "filament_z_hop_types": "array",
      "first_x_layer_fan_speed": "array",
      "from": "scalar",
      "full_fan_speed_layer": "array",
      "hole_coef_1": "array",
      "hole_coef_2": "array",
      "hole_coef_3": "array",
      "hole_limit_max": "array",
      "hole_limit_min": "array",
      "hot_plate_temp": "array",
      "hot_plate_temp_initial_layer": "array",
      "impact_strength_z": "array",
      "include": "array",
      "inherits": "scalar",
      "instantiation": "scalar",
      "long_retractions_when_ec": "array",
      "name": "scalar",
      "no_slow_down_for_cooling_on_outwalls": "array",
      "nozzle_temperature": "array",
      "nozzle_temperature_initial_layer": "array",
      "nozzle_temperature_range_high": "array",
      "nozzle_temperature_range_low": "array",
      "overhang_fan_speed": "array",
      "overhang_fan_threshold": "array",
      "override_process_overhang_speed": "array",
      "pre_start_fan_time": "array",
      "reduce_fan_stop_start_freq": "array",
      "required_nozzle_HRC": "array",
      "retraction_distances_when_ec": "array",
      "setting_id": "scalar",
      "slow_down_for_layer_cooling": "array",
      "slow_down_layer_time": "array",
      "slow_down_min_speed": "array",
      "supertack_plate_temp": "array",
      "supertack_plate_temp_initial_layer": "array",
      "temperature_vitrification": "array",
      "textured_plate_temp": "array",
      "textured_plate_temp_initial_layer": "array",
      "type": "scalar",
      "volumetric_speed_coefficients": "array"
    }
  }
} as const;
